### PR TITLE
process: fix raw_arg not showing up in docs

### LINKED ISSUE #5862: Make `Command::raw_arg` show up in docs
This method was added in #5704, but it does not show up in the documentation because it is windows-only. We need to fix that.

### PR DESCRIPTION
**Pull request by joriskleiber**
Should close #5862

### CODE REVIEW

File: tokio/src/process/mod.rs [hunk 1]
```diff
@@ -400,20 +400,20 @@ impl Command {
...
-    /// tokio's MSRV is sufficiently new. See [the documentation on
-    /// unstable features][unstable] for details about using unstable features.
-    #[cfg(windows)]
-    #[cfg(tokio_unstable)]
-    #[cfg_attr(docsrs, doc(cfg(all(windows, tokio_unstable))))]
-    pub fn raw_arg<S: AsRef<OsStr>>(&mut self, text_to_append_as_is: S) -> &mut Command {
-        self.std.raw_arg(text_to_append_as_is);
-        self
+    cfg_unstable_windows! {
+        /// [unstable]: crate#unstable-features
```
Comment (Darksonn) [inline tokio/src/process/mod.rs:404]: Please put this link at the bottom.

**Review by Darksonn — APPROVED** [review]
Thanks.
