### PR TITLE
Fix add_permits document

### LINKED ISSUE #2514: Semaphore: cannot add more than MAX_PERMITS permits
## Version

0.2.20

## Platform

`Linux 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux`

## Description

I tried to `add_permits(std::usize::MAX)` but got a panic:

    cannot add more than MAX_PERMITS permits (2305843009213693951)

It seems the `MAX_PERMITS` const should probably be exposed or at least it should be mentioned in the docs that you can't add `std::usize::MAX` permits...

### PR DESCRIPTION
**Pull request by NOVA-ME**
## Motivation
Fix the document.

## Solution
Add the ```MAX_PERMITS``` link
Example:
```rust
    /// Adds `n` new permits to the semaphore.
    ///
    /// `n` must less than [`MAX_PERMITS`]
    ///
    /// [`MAX_PERMITS`]: Semaphore::MAX_PERMITS
    pub fn add_permits(&self, n: usize) {
        self.ll_sem.release(n);
    }
````

### CODE REVIEW

File: tokio/src/sync/semaphore.rs [hunk 1]
```diff
@@ -80,6 +80,10 @@ impl Semaphore {
     }
 
     /// Adds `n` new permits to the semaphore.
+    ///
+    /// `n` must less than [`MAX_PERMITS`]
+    ///
+    /// [`MAX_PERMITS`]: Semaphore::MAX_PERMITS
     pub fn add_permits(&self, n: usize) {
```
Comment (Darksonn) [inline tokio/src/sync/semaphore.rs:87]: The link does not work as `MAX_PERMITS` is not public. We should write the actual number instead.

We should also avoid starting a sentence with \`n\`. Perhaps something like "The maximum number of permits is N. This function will panic if this number is exceeded."

Comment (NOVA-ME) [reply tokio/src/sync/semaphore.rs:87]:
```rust
    /// Adds `n` new permits to the semaphore.
    ///
    /// The maximum number of `n` is  2305843009213693951 (`std::usize::MAX >> 3`).
    ///
    /// And this function will panic if this number is exceeded.
```

Comment (Darksonn) [reply tokio/src/sync/semaphore.rs:87]: The limit is on the total number of permits, so it can panic even with `n = 10` as in [this example][1]. I would like to catch this nuance in the documentation.

[1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9eeaab3b04d24e954509dbdb64c445b1

Comment (NOVA-ME) [reply tokio/src/sync/semaphore.rs:87]:
````
    /// Adds `n` new permits to the semaphore.
    ///
    /// The maximum number of `n` must less than 2305843009213693951 - `the initial number of permits`.
    ///
    /// And this function will panic if this number is exceeded.
````
How about this.

Comment (Darksonn) [reply tokio/src/sync/semaphore.rs:87]: I think it would be simpler to just say

> The maximum number of permits is `usize::MAX >> 3`, and this function will panic if the limit is exceeded.

Comment (NOVA-ME) [reply tokio/src/sync/semaphore.rs:87]: Ok, got it. My English is poor, sorry.

Comment (NOVA-ME) [reply tokio/src/sync/semaphore.rs]: I've commit the new version of the document

File: tokio/src/sync/semaphore.rs [hunk 2]
```diff
@@ -78,8 +78,8 @@ impl Semaphore {
     pub fn available_permits(&self) -> usize {
         self.ll_sem.available_permits()
     }
-
-    /// Adds `n` new permits to the semaphore.
+    
+    /// The maximum number of permits is usize::MAX >> 3, and this function will panic if the limit is exceeded.
```
Comment (Darksonn) [inline tokio/src/sync/semaphore.rs:82]: The "Adds `n` new permits to the semaphore." should stay. Can you also add backticks around `usize::MAX >> 3`?

Comment (NOVA-ME) [reply tokio/src/sync/semaphore.rs]: I fixed it now.

**Comment by Darksonn** [comment]
Thank you! I will merge it if our automated checks say ok!

**Comment by NOVA-ME** [comment]
Thank you for your patience :heart: .
