### PR TITLE
Fix unnecessary zeroing for AsyncRead implementors

### LINKED ISSUE #2308: Several AsyncRead impls unnecessarily zero buffers in prepare_uninitialized_buffer
## Version

`tokio` 0.2.13

## Platform

This is an issue for all platforms.

## Subcrates

I haven't reviewed the full source, but I've reviewed `process` and can confirm that the `ChildStdout` and `ChildStderr` types are affected.

## Description

`ChildStdout` and `ChildStderr` implement `AsyncRead` by deferring to an internal `PollEvented` of a platform specific type: UNIX uses the standard library's child streams with `EventedFd` and Windows uses `NamedPipe` from `mio_named_pipes`. `PollEvented` naturally cannot implement `prepare_uninitialized_buffer` in any way other than zeroing, due to `std::io::Read::initializer` being unstable, however `ChildStdout` and `ChildStderr` use well-behaved types internally and should be known not to read from the buffer. Thus, the buffer needs not be initialized and `prepare_uninitialized_buffer` should be overwritten for these types to be a no-op.

Currently this bug affects me because I cannot call `prepare_uninitialized_buffer` due to the unacceptable zeroing, despite this being part of the contract of `AsyncRead` when an uninitialized buffer is involved. I just have to assume that the `tokio` implementation will remain well-behaved.

### PR DESCRIPTION
**Pull request by MikailBag**
Fixes #2308

### CODE REVIEW

File: tokio/src/io/async_read.rs [hunk 1]
```diff
@@ -5,6 +5,28 @@ use std::ops::DerefMut;
...
+    // to override `prepare_uninitialized_buffer`
+    /*use std::io::Read;
+    if !T::initializer::should_initialize() {
+        return false;
+    }
+    */
+    for x in buf {
+        // we could use safe method x.write(0) here, but it is unstable.
+        // Safety: as_mut_ptr() returns valid writeable pointer.
+        unsafe {
```
Comment (sfackler) [inline tokio/src/io/async_read.rs:23]: `*x = MaybeUninit::new(0);`

Comment (MikailBag) [reply tokio/src/io/async_read.rs]: I've updated both places.

**Comment by MikailBag** [comment]
How should I feature-gate prepare_uninitialized_buffer_std_read()?
I don't know which features should be used.

**Comment by Darksonn** [comment]
Oh, I didn't see that this exposes `prepare_uninitialized_buffer_std_read`. Is that really that useful?

**Comment by MikailBag** [comment]
I am not sure it is useful for outside users. I will make it private, then.

File: tokio/src/io/async_read.rs [hunk 2]
```diff
@@ -5,6 +5,26 @@ use std::ops::DerefMut;
 use std::pin::Pin;
 use std::task::{Context, Poll};
 
+/// Implements `AsyncRead::prepare_uninitialized_buffer` in a such a way
+/// that is valid for `R` requirements.
+/// Should be used to override `AsyncRead::prepare_uninitialized_buffer`
+/// for any AsyncRead impl which wraps an `std::io::Read` instance.
```
Comment (hawkw) [inline tokio/src/io/async_read.rs:11]: If this is going to be publicly exposed (and I'm not convinced it needs to be), it would be nice to have a more detailed comment explaining what it does and why users would want to use it...

**Comment by MikailBag** [comment]
I made that function private again, but I can't solve `#[cfg]` problems. These problems are definitely related to tests. I can't use plain `cfg`-s because tests want to override it. I can't use `cfg_*` macros as well because we need *OR* of `cfg_io_blocking` and `cfg_io_driver`, and nested macros effect in *AND*.

**Comment by MikailBag** [comment]
Alternatively, I can remove all feature-gates, and annotate that function with `#[allow(dead_code)]`, but I fear it would be very poor code style.

**Comment by Darksonn** [comment]
What's the issue with tests? I don't expect tests to successfully run without all features turned on. Anyway, if you can't find another way to fix it, I'm okay with `#[allow(dead_code)]`.

**Comment by MikailBag** [comment]
I expanded `prepare_uninitialized_buffer_std_read` documentation a bit and annotated with allow(dead_code). I think PR is now finished (except for awful commit history). Can I squash it now?

**Comment by Darksonn** [comment]
No, please leave the history intact. GitHub will ensure that the commit that ends up on master is properly squashed.

**Comment by MikailBag** [comment]
I think I finally understood why CI is failing.
test `fs_file_mocked` mocks all `tokio::io` APIs.
It `include!`s `src/fs/file.rs` and `src/io/blocking.rs`, and imports all other `tokio::io` items. However, `tokio::io::prepare_uninitialized_buffer_std_read` is *not* imported because it is pub(crate). So, when `Blocking` implementation is compiled in context of `fs_file_mocked` test (which has no access to private crate items), it can not find `crate::io::prepare_uninitialized_buffer_std_read`, and build [fails](https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=5935&view=logs&j=599d3a74-21de-5895-d5f3-2c3ca460a9ba&t=2771df71-2f65-52dd-eab4-0e1c9d0297e9&l=149).
I don't have good solution for this problem.
I can mark `prepare_uninitialized_buffer_std_read` as `pub` *and* `#[doc(hidden)]` with comment discouraging using this function, e.g. "this function is marked public for usage in tests. It is not part of API and should not be used outside of Tokio".
I can confirm that with this change `cargo test --all-features` succeeds (previsouly `fs_file_mocked` test would not compile).
I will now commit this change; I hope CI will finally pass :)

**Comment by Darksonn** [comment]
Maybe just delete the function and copy its body into `blocking`?

**Comment by MikailBag** [comment]
Thanks, I implemented your approach, it really looks better that doc(hidden) public item.

**Comment by MikailBag** [comment]
I was told in Discord that PollEvented will likely be excluded from Tokio 0.3, and Read::initializer is unlikely to be stabilized before that.
It means all machinery introduced in this PR will not have any benefit, so I'm going to rollback prepare_uninitialized_buffer_std_read function at all.
