### PR TITLE
tests: fix ping pong saturation

### LINKED ISSUE #3305: Fix ping_pong_saturation test
I got the following panic when running the test suite:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:thread '38tokio-runtime-worker
' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054thread ':tokio-runtime-worker38' panicked at '
called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())called `Result::unwrap()` on an `Err` value: SendError(())', ', tokio/tests/rt_common.rstokio/tests/rt_common.rs::10541054::3838

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
test threaded_scheduler_4_threads::ping_pong_saturation ... ok
```

### PR DESCRIPTION
**Pull request by blasrodri**
Signal the tasks driving the ping pong to stop running after spawning
a few others. After that, awaits for each of them to ensure that all ran properly.

Fixes #3305

### CODE REVIEW

File: tokio/tests/rt_common.rs [hunk 1]
```diff
@@ -1021,39 +1021,45 @@ rt_test! {
     // other tasks.
     #[test]
     fn ping_pong_saturation() {
+        use std::{mem::drop, sync::atomic::{Ordering, AtomicBool}};
```
Comment (Darksonn) [inline tokio/tests/rt_common.rs:1024]: The prelude already has `drop`.
```suggestion
        use std::sync::atomic::{Ordering, AtomicBool};
```

File: tokio/tests/rt_common.rs [hunk 2]
```diff
@@ -1021,39 +1021,45 @@ rt_test! {
...
-                task::spawn(async move {
-                    loop {
-                        rx1.recv().await.unwrap();
+                    // Close the channel and wait for the other task to exit.
+                    drop(tx1);
+                    assert!(rx2.recv().await.is_none());
+                }));
+
+                tasks.push(task::spawn(async move {
+                    while rx1.recv().await.is_some(){
```
Comment (Darksonn) [inline tokio/tests/rt_common.rs:1059]: Hm, I wonder why rustfmt didn't catch this. Can you please run the test through rustfmt?
```suggestion
                    while rx1.recv().await.is_some() {
```

File: tokio/tests/rt_common.rs [hunk 3]
```diff
@@ -1021,39 +1021,45 @@ rt_test! {
     // other tasks.
     #[test]
     fn ping_pong_saturation() {
+        use std::{sync::atomic::{Ordering, AtomicBool}};
```
Comment (Darksonn) [inline tokio/tests/rt_common.rs:1024]:
```suggestion
        use std::sync::atomic::{Ordering, AtomicBool};
```

Comment (Darksonn) [reply tokio/tests/rt_common.rs:1024]: You know, rustfmt should have caught this.

Comment (blasrodri) [reply tokio/tests/rt_common.rs:1024]: I'm running the rustfmt but nothing shows up... Am I doing something wrong?
```
rustfmt --check --edition 2018 $(find . -name '*.rs' -print)
```

Comment (Darksonn) [reply tokio/tests/rt_common.rs]: It's probably because of the `rt_test!` macro around it.

**Review by Darksonn — APPROVED** [review]
