### PR TITLE
io: add budgeting to tokio::runtime::io::registration::async_io

### LINKED ISSUE #4782: Tokio in current_thread not releasing open file handles once the limit is reached.
**Version**

`cargo tree | grep tokio`
```
└── tokio v1.19.2
    └── tokio-macros v1.8.0 (proc-macro)
```
**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
```
Linux pdebian 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
```

**Description**

While reading from a Unix Socket over a buffered stream, the tokio executor in current_thread doesn't release open files once the open file OS limit is hit and will not accept any more incoming requests, but if the number of open files stays within the OS limit, the file handles are released.

If the executor is switched to a multi_threaded one, this issue doesn't happen. Although the open file limits are hit, it frees the openfiles and the program continues to work.

I am not sure if I am using the BufStream wrong or I might have overlooked something.

I tried this code:

## A minimal version of the server code that accepts connection over a unix socket and prints it

`src/main.rs`
```rust
use anyhow::{Context, Result};
use clap::{App, Arg};
use env_logger::{Builder, Env};
use log::{error, info};
use tokio::{
    io::{AsyncBufReadExt, AsyncWriteExt, BufStream},
    net::{UnixListener, UnixStream},
    runtime,
    // time::{timeout, Duration},
};

pub static SOCK_PATH: &str = "/var/run/sock.sock";

fn main() -> Result<()> {
    Builder::from_env(Env::default().default_filter_or("info")).init();
    let clap_app = App::new("openfiles")
        .version(env!("CARGO_PKG_VERSION"))
        .author(env!("CARGO_PKG_AUTHORS"))
        .about("checking tokio openfiles")
        .arg(
            Arg::new("worker-threads")
                .long("worker-threads")
                .takes_value(true)
                .help("number of worker threads. 0 = current_thread. >0 = worker_threads")
                .default_value("1")
                .global(true),
        )
        .get_matches();
    let threads = clap_app
        .value_of("worker-threads")
        .unwrap()
        .parse::<usize>()
        .unwrap();
    let rt = match threads {
        0 => {
            info!("running in current thread");
            runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .context("cannot create runtime")?
        }
        multi => {
            info!("worker_threads: {}", multi);
            runtime::Builder::new_multi_thread()
                .worker_threads(multi)
                .enable_all()
                .thread_name("foobar")
                .build()
                .context("cannot create runtime")?
        }
    };

    let handle = rt.handle();
    let _enter_guard = handle.enter();
    let _ = std::fs::remove_file(SOCK_PATH);
    let listener = UnixListener::bind(SOCK_PATH).unwrap();
    rt.block_on(async move { run_listener(listener).await });
    Ok(())
}

pub async fn run_listener(listener: UnixListener) {
    loop {
        match listener.accept().await {
            Ok((stream, _)) => {
                info!("Received incoming");
                tokio::task::spawn(async move {
                    match handle_client(stream).await {
                        Ok(_) => (),
                        Err(err) => error!("error handling client, error: {}", err),
                    }
                });
            }
            Err(err) => {
                error!("error accepting connection, error: {}", err);
            }
        }
    }
}

async fn handle_client(stream: UnixStream) -> Result<()> {
    let mut buf_stream = BufStream::new(stream);
    let mut line = String::new();
    buf_stream.read_line(&mut line).await?;

    info!("Received request: {}", line);
    buf_stream.write_all(b"END\r\n").await?;
    buf_stream.shutdown().await?;
    drop(buf_stream);
    Ok(())
}

```

## Client code that generates parallel requests

`src/client/main.rs`
```rust
use anyhow::{Context, Result};
use tokio::{
    io::{AsyncWriteExt, BufStream},
    net::UnixStream,
    runtime,
};

pub static SOCK_PATH: &str = "/var/run/sock.sock";

fn main() -> Result<()> {
    let rt = runtime::Builder::new_multi_thread()
        .enable_all()
        .thread_name("resolver-core")
        .build()
        .context("cannot create runtime")?;
    rt.block_on(run_client())?;

    Ok(())
}

async fn run_client() -> Result<()> {
    loop {
        let listener = UnixStream::connect(SOCK_PATH).await?;
        let mut buf_stream = BufStream::new(listener);
        tokio::spawn(async move {
            match buf_stream.write_all(b"foobar\r\n").await {
                Ok(_) => (),
                Err(err) => {
                    println!("write_all error:: {}", err);
                }
            };

            match buf_stream.flush().await {
                Ok(_) => (),
                Err(err) => {
                    println!("flush error:: {}", err);
                }
            };
        });
    }
}

```

## cargo.toml

```toml
[package]
name = "foobar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
clap = "3.0.13"
anyhow = "1.0.54"
log = "0.4.17"
env_logger = "0.9.0"

```

I expected to see this happen:

When the server is run as 
```
./server --worker-threads=0
```

and when the client is run as
```
./client
```
I expect to see 

```
[2022-06-21T19:55:57Z ERROR server] error accepting connection, error: Too many open files (os error 24)
```
from the server's stdout once the `ulimit` to openfiles are hit, but I also expect it to recover after the client is stopped.

Instead, this happened: 

With the above code, the server keeps on printing 
```
[2022-06-21T19:55:57Z ERROR server] error accepting connection, error: Too many open files (os error 24)
```
even after the client is exited. I watched the output of `lsof` for some time and it was as below 

```
sudo lsof -p 2704488 | grep -ic sock
1015
```
The number of open file handles to the socket never comes down because it was never released.

### Note: 
This happens only when running in `current_thread`. If the executer is switched to `multi_threaded` by running the server as
`./server --worker-threads=1`, even if the server hits open file limit, it recovers and `lsof` output shows the number of open filehandles to the socket coming down.
I tried to reproduce this in a docker running on my mac, but it didn't occur. I tried running this on baremetal linux and linux running on vmware fusion and I was able to reproduce this.
I have this code added into my repo if anybody want to try it locally on a linux machine. (https://github.com/nohupped/buggy)

### LINKED ISSUE #5946: Datagram sockets do not appear to participate in cooperative multitasking
**Version**
tokio 1.31.0

**Platform**
`uname -a`: `Linux enterprise 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Description**

It seems like Unix datagram sockets don't correctly participate in cooperative multitasking. When a task continuously recv()s from a Unix datagram socket and there is always a datagram available in the socket, the recv() never blocks, the runtime never forces it to yield and the task never yields. Therefore, other tasks never have an opportunity to run.

In the following small program, I expect to see the debug representation of a std::time::SystemTime printed about every 250ms. When receiving an endless stream of Unix datagrams from 2 or 3 other processes running full tilt, I instead see one every second or every few seconds.

Our example uses a single-threaded runtime, but it also affects a multi-threaded runtime, which we observed as inconsistent but common delays in other tasks being run that happened to be scheduled on the same thread as the datagram recv() task.

```rust
use std::time::Duration;

use tokio::net::UnixDatagram;

// Single thread to better demonstrate the issue
#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<_> = std::env::args().collect();

    // Sending process runs only this, sends datagrams forever
    if args[1] == "sender" {
        // Wait until the receiver opens the socket
        tokio::time::sleep(Duration::from_millis(250)).await;
        let bytes = b"hello, tokio!";
        let tx = UnixDatagram::unbound()?;
        tx.connect("socket")?;
        loop {
            tx.send(bytes).await?;
        }
    } else {
        // Delete socket from past run
        let _ = tokio::fs::remove_file("socket").await;
        let rx = UnixDatagram::bind("socket")?;
        // Task that reads forever as fast as the socket will give it datagrams
        let a = tokio::task::spawn(async move {
            let mut buf = [0_u8; 13];
            loop {
                // Uncomment to fix
                //tokio::task::yield_now().await;
                rx.recv(&mut buf).await.unwrap();
                assert_eq!(&buf, b"hello, tokio!");
            }
        });
        // This task shows how often the runtime forces the above task to yield
        // Without the explicit yield, it's starved
        let b = tokio::task::spawn(async move {
            loop {
                tokio::time::sleep(Duration::from_millis(250)).await;
                println!("It's {:?}", std::time::SystemTime::now());
            }
        });
        let (_, _) = tokio::join!(a, b);
    }
    Ok(())
}
```

This is the output with the explicit yield, and what I would expect:

```
tokio_brokio on  main [?] is 📦 v0.1.0 via 🦀 v1.66.1 
❯ ./target/release/tokio_brokio recv & ./target/release/tokio_brokio sender & ./target/release/tokio_brokio sender & ./target/release/tokio_brokio sender             
[1] 3297719
[2] 3297720
[3] 3297721
It's SystemTime { tv_sec: 1692908737, tv_nsec: 224419890 }
It's SystemTime { tv_sec: 1692908737, tv_nsec: 475419527 }
It's SystemTime { tv_sec: 1692908737, tv_nsec: 726420228 }
It's SystemTime { tv_sec: 1692908737, tv_nsec: 977419866 }
It's SystemTime { tv_sec: 1692908738, tv_nsec: 228420222 }
It's SystemTime { tv_sec: 1692908738, tv_nsec: 479420486 }
It's SystemTime { tv_sec: 1692908738, tv_nsec: 730419806 }
It's SystemTime { tv_sec: 1692908738, tv_nsec: 981420162 }
It's SystemTime { tv_sec: 1692908739, tv_nsec: 232420042 }
It's SystemTime { tv_sec: 1692908739, tv_nsec: 483419352 }
It's SystemTime { tv_sec: 1692908739, tv_nsec: 734420485 }
It's SystemTime { tv_sec: 1692908739, tv_nsec: 985420387 }
It's SystemTime { tv_sec: 1692908740, tv_nsec: 236419035 }
It's SystemTime { tv_sec: 1692908740, tv_nsec: 487420190 }
It's SystemTime { tv_sec: 1692908740, tv_nsec: 738419797 }
It's SystemTime { tv_sec: 1692908740, tv_nsec: 989420219 }
It's SystemTime { tv_sec: 1692908741, tv_nsec: 240419320 }
It's SystemTime { tv_sec: 1692908741, tv_nsec: 491419883 }
It's SystemTime { tv_sec: 1692908741, tv_nsec: 742422658 }
```

This is the output without the explicit yield, showing that the timer task is starved of execution time

```
tokio_brokio on  main [?] is 📦 v0.1.0 via 🦀 v1.66.1
❯ ./target/release/tokio_brokio recv & ./target/release/tokio_brokio sender & ./target/release/tokio_brokio sender & ./target/release/tokio_brokio sender  
[1] 3296885
[2] 3296886
[3] 3296887
It's SystemTime { tv_sec: 1692908693, tv_nsec: 984578213 }
It's SystemTime { tv_sec: 1692908695, tv_nsec: 980149233 }
It's SystemTime { tv_sec: 1692908696, tv_nsec: 980901379 }
It's SystemTime { tv_sec: 1692908700, tv_nsec: 943152097 }
It's SystemTime { tv_sec: 1692908701, tv_nsec: 277230897 }
```

Co-authored with @jvranish

### PR DESCRIPTION
**Pull request by Noah-Kennedy**
Fixes #5946. 
Fixes #4782.

This change adds budgeting to most of the remaining unbudgeted IO operations which can complete instantly, including datagram send/recv operations and listener socket accepts.

This is particularly significant for scenarios in which resource limits are hit, as it can be common for things like listener tasks to spin when receiving errors and just log them, busy looping worker threads which might otherwise be handling existing connections and closing them.

This can also sometimes lead to complex failure scenarios within datagram systems experiencing resource exhaustion.

### CODE REVIEW

**Comment by Noah-Kennedy** [comment]
Note: this is being backported, so do not merge.

I will merge it manually on the command line.

File: tokio/src/runtime/io/registration.rs [hunk 1]
```diff
@@ -219,11 +219,17 @@ impl Registration {
...
+
             match f() {
                 Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
                     self.clear_readiness(event);
                 }
-                x => return x,
+                x => {
+                    coop.made_progress();
+
+                    return x;
```
Comment (Darksonn) [inline tokio/src/runtime/io/registration.rs:231]: This affects only things that use `async_io`. I believe that we discussed a different fix on one of the issues, which is the following:

 * Polling for readiness returns Pending on missing coop budget, but does not consume budget.
 * IO operations, even non-async ones, consume a budget, but do not check it.

With the above change, `async_io` would get the right behavior automatically.

Comment (Noah-Kennedy) [reply tokio/src/runtime/io/registration.rs:231]: This feels like the correct way to do the accounting, but I'm worried it might lead to more significant changes in behavior than we may intend (e.g many users might be expecting try_ ops to not touch the buget).

Perhaps we can use this current method for the patch releases, and then the other method for the next minor version release we do?

Comment (Darksonn) [reply tokio/src/runtime/io/registration.rs:231]: That works for me.

File: tokio/tests/coop_budger.rs [hunk 2]
```diff
@@ -0,0 +1,77 @@
+#![warn(rust_2018_idioms)]
```
Comment (dimitarvp) [inline tokio/tests/coop_budger.rs:1]: Should this file be called `core_budger.rs`? Should it not be `core_budget.rs` (notice the "t" at the end and not "r")?

Comment (Darksonn) [reply tokio/tests/coop_budger.rs:1]: Ah, nice catch. Do you want to submit a PR that fixes it?

Comment (dimitarvp) [reply tokio/tests/coop_budger.rs:1]: Admittedly not, my apologies. Just a drive-by observation as I am clocking out of work.

Comment (Darksonn) [reply tokio/tests/coop_budger.rs:1]: #6234

Comment (Noah-Kennedy) [reply tokio/tests/coop_budger.rs:1]: once again, the keyboard on the new laptop has bested me
