### PR TITLE
time: fix DelayQueue rewriting delay on insert after Poll::Ready

### LINKED ISSUE #1700: inserting a new item into a delay queue always waits for that new item even if the queue already contained earlier expiring items
## Version

tokio v0.1.22

## Platform

Linux hush 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux

## Subcrates

tokio::timer

## Description

inserting items into a delay queue after it is already running causes the delay queue to not be woken up until the newly inserted item is ready, even if there were previously other items that would have woken up earlier. example code:

```
use futures::stream::Stream as _;

struct ThingWithDelayQueue {
    delay_queue: tokio::timer::DelayQueue<u8>,
    did_thing: bool,
}

impl ThingWithDelayQueue {
    fn new() -> Self {
        let mut delay_queue = tokio::timer::DelayQueue::new();
        delay_queue.insert(1, std::time::Duration::from_secs(1));
        delay_queue.insert(2, std::time::Duration::from_secs(2));
        delay_queue.insert(3, std::time::Duration::from_secs(3));
        delay_queue.insert(4, std::time::Duration::from_secs(4));
        delay_queue.insert(5, std::time::Duration::from_secs(5));
        Self {
            delay_queue,
            did_thing: false,
        }
    }
}

impl futures::stream::Stream for ThingWithDelayQueue {
    type Item = ();
    type Error = ();

    fn poll(&mut self) -> futures::Poll<Option<Self::Item>, Self::Error> {
        if let Some(expired) =
            futures::try_ready!(self.delay_queue.poll().map_err(|_| ()))
        {
            let thing = expired.into_inner();
            log::error!("event happened: {}", thing);
            if !self.did_thing {
                self.did_thing = true;
                self.delay_queue
                    .insert(10, std::time::Duration::from_secs(10));
            }
            Ok(futures::Async::Ready(Some(())))
        } else {
            log::error!("done");
            Ok(futures::Async::Ready(None))
        }
    }
}

fn main() {
    env_logger::init();
    log::error!("start");
    tokio::run(ThingWithDelayQueue::new().for_each(|_| Ok(())))
}
```

this code produces this output:

```
[2019-10-28T06:12:25Z ERROR delay_queue_bug] start
[2019-10-28T06:12:26Z ERROR delay_queue_bug] event happened: 1
[2019-10-28T06:12:36Z ERROR delay_queue_bug] event happened: 2
[2019-10-28T06:12:36Z ERROR delay_queue_bug] event happened: 3
[2019-10-28T06:12:36Z ERROR delay_queue_bug] event happened: 4
[2019-10-28T06:12:36Z ERROR delay_queue_bug] event happened: 5
[2019-10-28T06:12:36Z ERROR delay_queue_bug] event happened: 10
[2019-10-28T06:12:36Z ERROR delay_queue_bug] done
```

but if you comment out the `self.delay_queue.insert(10, std::time::Duration::from_secs(10));` line, you get this output as expected:

```
[2019-10-28T06:13:37Z ERROR delay_queue_bug] start
[2019-10-28T06:13:38Z ERROR delay_queue_bug] event happened: 1
[2019-10-28T06:13:39Z ERROR delay_queue_bug] event happened: 2
[2019-10-28T06:13:40Z ERROR delay_queue_bug] event happened: 3
[2019-10-28T06:13:41Z ERROR delay_queue_bug] event happened: 4
[2019-10-28T06:13:42Z ERROR delay_queue_bug] event happened: 5
[2019-10-28T06:13:42Z ERROR delay_queue_bug] done
```

### PR DESCRIPTION
**Pull request by nolanderc**
## Motivation

Fixes #1700 

## Solution

Previously, inserting a new item into a `DelayQueue` after a value expired would result in all items in the queue to be postponed until the inserted item was ready. This was due to a delay keeping track of when the next item expires wasn't being updated correctly when a value was extracted from the wheel. 

This PR makes sure that when a item expires, the `DelayQueue` updates the delay until the next item expires accordingly.

### CODE REVIEW

File: tokio/src/time/delay_queue.rs [hunk 1]
```diff
@@ -724,6 +724,9 @@ impl<T> DelayQueue<T> {
             self.delay = None;
 
             if let Some(idx) = self.wheel.poll(&mut self.poll, &mut self.slab) {
+                if let Some(deadline) = self.next_deadline() {
+                    self.delay = Some(delay_until(deadline));
+                }
```
Comment (kleimkuhler) [inline tokio/src/time/delay_queue.rs]: This function is already a little tough to follow without understanding most of the `DelayQueue` implementation. 

Instead of putting another `next_deadline()` in here, how about we set it in line 724--something like this:

```
self.delay = self.next_deadline().map(|deadline| delay_until(deadline));

if let Some(idx) = self.wheel.poll(&mut self.poll, &mut self.slab) {
    return Poll::Ready(Some(Ok(idx)))
}

if self.delay.is_none() {
    return Poll::Ready(None)
}
```

This ensures the next deadline is already set before checking if another item can be returned or completing if the queue is done.

Comment (nolanderc) [reply tokio/src/time/delay_queue.rs]: I did think about that, however, as far as I could tell `next_deadline` returns the next instant in the wheel. If that's the case, we need to ensure that we `poll` the wheel first, since otherwise the value instant by `next_deadline` would be the same as the value we just polled, causing an unecesasry wakeup in the future.

I agree that `poll_idx` is a little convoluted, I'll see what I can do.

Comment (kleimkuhler) [reply tokio/src/time/delay_queue.rs]: Yep that makes sense. Cleanup looks good!
