### PR TITLE
Fix CTRL_CLOSE, CTRL_LOGOFF and CTRL_SHUTDOWN on windows

### LINKED ISSUE #7039: Tokio::signals::windows - are windows signals correctly handled?
**Version**
v1.42.0

**Platform**
Windows

**Description**
The issue was been discussed in another tokio-dependent crate. 
Full discussion here: https://github.com/Finomnis/tokio-graceful-shutdown/issues/94#issuecomment-2545738526

In tokio, in this section:
https://github.com/tokio-rs/tokio/blob/10e23d1c621ab38aadf2cefba1120494cff615f0/tokio/src/signal/windows/sys.rs#L109

```
unsafe extern "system" fn handler(ty: u32) -> BOOL {
    let globals = globals();
    globals.record_event(ty as EventId);

    // According to https://docs.microsoft.com/en-us/windows/console/handlerroutine
    // the handler routine is always invoked in a new thread, thus we don't
    // have the same restrictions as in Unix signal handlers, meaning we can
    // go ahead and perform the broadcast here.
    if globals.broadcast() {
        1
    } else {
        // No one is listening for this notification any more
        // let the OS fire the next (possibly the default) handler.
        0
    }
}
```

The [HandlerRoutine](https://learn.microsoft.com/en-us/windows/console/handlerroutine) is will defined. It later gets registered via the [SetConsoleCtrlHandler](https://learn.microsoft.com/en-us/windows/console/setconsolectrlhandler). This gets done in the `tokio` code [here](https://github.com/tokio-rs/tokio/blob/10e23d1c621ab38aadf2cefba1120494cff615f0/tokio/src/signal/windows/sys.rs#L96). 

According to: 
[HandlerRoutine reference](https://learn.microsoft.com/en-us/windows/console/handlerroutine)

It seems that if the handler returns `1`, then the console understands this as the handler having handled the graceful closure of the program, and windows terminates the program. If 0 is passed, "next handler function in the list of handlers for this process is used". [SetConsoleCtrlHandler reference](https://learn.microsoft.com/en-us/windows/console/setconsolectrlhandler):
> When a console process receives any of the control signals, its handler functions are called on a last-registered, first-called basis until one of the handlers returns TRUE. If none of the handlers returns TRUE, the default handler is called.

But in the tokio-defined handler function, `broadcast()` is called, which "Returns `true` if an event was delivered to at least one listener". But then broadcast() evaluates to true, the handler function returns `true`, telling windows that the defined handler handled the signal. 

- If we are dealing with a `CtrlC` signal, I guess this should be fine. The handler informs Windows that the signal has been handled, and windows doesn't call the default handler, which would terminate the program.
- However, if we are dealing with a with something like a `CTRL_CLOSE_EVENT`, `CTRL_LOGOFF_EVENT`, or `CTRL_SHUTDOWN_EVENT`, according to the [HandlerRoutine reference](https://learn.microsoft.com/en-us/windows/console/handlerroutine), Windows immediately terminates the process once a `true` return is received (unlike `CTRL_C`events 

It seems that the way `tokio` implements it doesn't even give a change for the program to do anything with the signal in the case of `CTRL_CLOSE_EVENT`, `CTRL_LOGOFF_EVENT`, or `CTRL_SHUTDOWN_EVENT` events, since it broadcasts it to the listeners, and if they exist, the handler function returns a true, resulting in Windows terminating the program right away?

Or am I misinterpreting something in the Tokio code?

### How to fix?
If I interpreted the Tokio mechanism correctly, then I guess the way to fix would be something like making the handler function wait for the program to complete.

One of the limiting factors is that, when the console emits `CTRL_CLOSE_EVENT`, `CTRL_LOGOFF_EVENT`, or `CTRL_SHUTDOWN_EVENT`, Windows grants a limited time for the program to clean itself: [Timeouts](https://learn.microsoft.com/en-us/windows/console/handlerroutine#timeouts).

The `CTRL_CLOSE_EVENT` timeout is 5 s, for example. If the program is not done cleaning after these 5 seconds, it will be forcefully terminated.

Possible solutions:
1) Make the handler return `false` always, telling the user to register another handler function, with the cleanup he wants to do. Also tell the user that his handler function must be defined BEFORE the Tokio signal is registered, if the signal is to be of any use as well (due to the last-registered, first-called).
2) Put a sleep on Tokio's handler function, so that that function never returns, and the program always has the full timeout time to clean after itself. Sleep works because the handler is run in another thread, so wouldn't affect the main thread.
3) Some smarter method where the handler stops on some synchronization flag, that then can be switched by the main thread when the cleanup is done, and then lets the handler function proceed and finalize.

EDIT: possibly it is a good idea to always return False, regardless of the fix above. This will allow the user to keep defining custom CtrlHandler functions to be long alongside tokio's, if he so wishes (with the ordering warning mentioned in (1). This would invalidate approach (2) however, which won't give time for other handlers to run. 

(1) is probably the most hacky. (2) would integrate the most seamlessly, however, preventing the user from running their own ctrl handlers. (3) is probably the most solid, but would imply having a synchronization variable, and some kind of action from the program that it is done cleaning itself. This would however result in code that is not cross-platform in the sense that this synchronization is not needed with Unix signals.

### PR DESCRIPTION
**Pull request by Finomnis**
Fixes #7039.

## Motivation

According to https://learn.microsoft.com/en-us/windows/console/handlerroutine#remarks, the windows signals `CTRL_CLOSE`, `CTRL_LOGOFF` and `CTRL_SHUTDOWN` immediately kill the process upon being handled.

The intention is that the handler of those signals performs cleanup tasks, and once completed, it returns and the process is killed.

This behavior is sadly not really compatible with an async system that is based on signals.

## Solution

There are multiple possible ways to solve this; the easiest one being to simply never return from the handler thread. This works because Rust calls `ExitProcess` after its main (to my knowledge). I tested it on a project of mine, and it seems to work indeed.

### CODE REVIEW

File: tokio/src/signal/windows/sys.rs [hunk 1]
```diff
@@ -114,7 +129,15 @@ unsafe extern "system" fn handler(ty: u32) -> BOOL {
     // the handler routine is always invoked in a new thread, thus we don't
     // have the same restrictions as in Unix signal handlers, meaning we can
     // go ahead and perform the broadcast here.
-    if globals.broadcast() {
+    let event_was_handled = globals.broadcast();
+
+    if event_requires_infinite_sleep_in_handler(ty) {
+        loop {
+            std::thread::sleep(std::time::Duration::MAX);
```
Comment (Darksonn) [inline tokio/src/signal/windows/sys.rs:136]:
```suggestion
            std::thread::park();
```

**Comment by dsherret** [comment]
Thanks for doing this. I tested this with CTRL_CLOSE and it works for me. FWIW, this is the same solution that libuv does: https://github.com/libuv/libuv/blob/23632e9104b6506d5bee0d85b807c2351617d226/src/win/signal.c#L130

**Comment by Finomnis** [comment]
@dsherret Actually, it doesn't. It only sleeps if someone handles the event, we should do that as well.

**Comment by Finomnis** [comment]
@dsherret would you mind treating the PR again now?

**Comment by dsherret** [comment]
Yup, still works.

**Comment by Finomnis** [comment]
@Darksonn Ready for another review

**Comment by Finomnis** [comment]
@Darksonn I'm not 100% sure if we should always do the infinite wait, or only if somebody received the event.

It makes sense that if nobody receives it, nothing will actually react to the event; at least I thought so. But then I saw how the tests are layed out; they seem to first produce the event and then receive it. Does that mean people can receive the event even if `globals.broadcast()` returns `0`? If so, we should revert the conditional to that in the infinite loop again.

**Comment by Darksonn** [comment]
Why do we handle all three this way when libuv only does it for one of them?

**Comment by Finomnis** [comment]
> Why do we handle all three this way when libuv only does it for one of them?

Why does libuv only handle one?
They say something about services, do we have a separate windows service interface?

**Comment by Finomnis** [comment]
Either way, the other two signals are completely pointless for Tokio of we don't handle them like this, according to the windows api docs. They also result in an immediate kill after returning from the handler.

File: tokio/src/signal/windows/sys.rs [hunk 2]
```diff
@@ -177,9 +200,9 @@ mod tests {
             // Windows doesn't have a good programmatic way of sending events
             // like sending signals on Unix, so we'll stub out the actual OS
             // integration and test that our handling works.
-            unsafe {
+            std::thread::spawn(|| unsafe {
```
Comment (Darksonn) [inline tokio/src/signal/windows/sys.rs:203]: Can you add a comment explaining why we do this? (In all three tests.)

Or perhaps you should even have a shared function for calling the handler that checks `event_requires_infinite_sleep_in_handler` and does thread spawn or not depending on the value.

**Review by Darksonn — COMMENTED** [review]
Overall LGTM, just some comments on tests.

**Comment by Darksonn** [comment]
cc @ipetkov please review

File: tokio/src/signal/windows/sys.rs (hunk 2 above)
Comment (Finomnis) [reply tokio/src/signal/windows/sys.rs]: Like this?

Comment (Darksonn) [reply tokio/src/signal/windows/sys.rs]: Yes, thanks.

File: tokio/src/signal/windows/sys.rs [hunk 3]
```diff
@@ -114,7 +129,15 @@ unsafe extern "system" fn handler(ty: u32) -> BOOL {
...
     // have the same restrictions as in Unix signal handlers, meaning we can
     // go ahead and perform the broadcast here.
-    if globals.broadcast() {
+    let event_was_handled = globals.broadcast();
+
+    if event_was_handled && event_requires_infinite_sleep_in_handler(ty) {
+        loop {
+            std::thread::park();
+        }
+    }
```
Comment (ipetkov) [inline tokio/src/signal/windows/sys.rs:138]: Instead of doing a `event_requires_infinite_sleep_in_handler` check a second time here, move this bit of logic inside of `raise_event` (that's the place that already decides whether to spin up a new thread, so it already knows whether it is safe to permanently park the thread there

**Review by ipetkov — COMMENTED** [review]
I don't have the means to test this myself, but since others have commented this works for them I'll trust that its helping!

File: tokio/src/signal/windows/sys.rs (hunk 3 above)
Comment (Finomnis) [reply tokio/src/signal/windows/sys.rs:138]: I think you misunderstand; `raise_event` is a test function, this is the actual code.

Comment (ipetkov) [reply tokio/src/signal/windows/sys.rs:138]: Ah yes this is the test code, apologies! Been a few years since I've looked at this code :sweat_smile:

**Review by ipetkov — APPROVED** [review]

**Comment by Astlaan** [comment]
I can test it tomorrow if needed

**Comment by Finomnis** [comment]
> I can test it tomorrow if needed

Yes, please.

**Comment by Astlaan** [comment]
Maybe I'm just too tired right now, but shouldn't this work:
https://github.com/Astlaan/test-tokio-ctrl-close/blob/main/src/main.rs

**Comment by dsherret** [comment]
What's the actual behaviour? (I'm AFK atm. My guess is it creates a single file and exits, which is fine I think?)

**Comment by Finomnis** [comment]
> Maybe I'm just too tired right now, but shouldn't this work?: https://github.com/Astlaan/test-tokio-ctrl-close/blob/main/src/main.rs

Yes, it should create 4-5 files and then be killed.

I'm not sure why, but in my own tests it seemed to work in cmd, but not in powershell.

**Comment by Finomnis** [comment]
@Astlaan is it the same behavior I described here? https://github.com/tokio-rs/tokio/issues/7039#issuecomment-2613798410

**Comment by Finomnis** [comment]
@dsherret You said it works, right? I'd merge anyway if @Astlaan does not respond

**Comment by dsherret** [comment]
Yes, it works for me.

By the way, that example correctly creates 4-5 files on both cmd and powershell from windows terminal and windows console host. Also, I see now that 4-5 files is the expected behaviour because there's a 5000ms timeout before windows kills the process.

**Comment by Astlaan** [comment]
> Yes, it works for me.
> 
> By the way, that example correctly creates 4-5 files on both cmd and powershell from windows terminal and windows console host. Also, I see now that 4-5 files is the expected behaviour because there's a 5000ms timeout before windows kills the process.

Are you using my code? Because for me I see no files being created at all.

**Comment by dsherret** [comment]
Yup. What terminal are you using?

**Comment by Astlaan** [comment]
> Yup. What terminal are you using?

I tried with both cmd and powershell.
I opened them in the repo, then ran "cargo run", click the close button in the powershell, but no files were created.

**Comment by dsherret** [comment]
Try `cargo build` and launch the executable directly. I think maybe `cargo run` is preventing it from receiving the signal. I’m not at my computer right now, but I ran the executable directly.

Also, is cmd and powershell being launched with windows console host? Does it work for you in windows terminal with cmd and powershell? I think windows console host/windows terminal is what sends the event.

**Comment by Astlaan** [comment]
> Try `cargo build` and launch the executable directly. I think maybe `cargo run` is preventing it from receiving the signal. I’m not at my computer right now, but I ran the executable directly.

This was the issue indeed. It runs fine if I run it directly.
