### PR TITLE
Fix a deadlock that can happen when shutting down

### LINKED ISSUE #401: Deadlock when dropping the runtime
Reported by @jonhoo 

Trace: https://gist.github.com/jonhoo/d898ca9e93fe851271a5aeaa31d4a7d2

### PR DESCRIPTION
**Pull request by carllerche**
There is a deadlock that can occur when the concurrent runtime shuts
down. This patch adds a test and fix.

Fixes #401.

### CODE REVIEW

File: tokio-reactor/src/lib.rs [hunk 1]
```diff
@@ -392,23 +392,41 @@ impl Reactor {
         let aba_guard = token.0 & !MAX_SOURCES;
         let token = token.0 & MAX_SOURCES;
 
-        let io_dispatch = self.inner.io_dispatch.read().unwrap();
+        let mut rd = None;
+        let mut wr = None;
```
Comment (olix0r) [inline tokio-reactor/src/lib.rs]: tioli.. you could avoid the mut vars with

```rust
let (rd, wr) = {
    ...
    let wr = if ready.is_writable() || platform::is_hup(&ready) {
        io.writer.take_to_notify()
    } else {
        None
    };
    let rd = if !(ready & (!mio::Ready::writable())).is_empty() {
        io.reader.take_to_notify()
    } else {
        None
    };

    (rd, wr)
};
```

Comment (carllerche) [reply tokio-reactor/src/lib.rs]: I had that first, but I thought the mut vars was more readable 🤷‍♂️
