### PR TITLE
sync: clarify the behavior of `tokio::sync::watch::Receiver`

### LINKED ISSUE #7281: `tokio::sync::watch::Receiver`  does not adhere to the specification
**Version**
```
└── tokio v1.44.2
    └── tokio-macros v2.5.0 (proc-macro)
```

**Platform**
`Linux beroal 6.14.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 20 Apr 2025 12:38:52 +0000 x86_64 GNU/Linux`

**Description**

Hi. When exploring whether `Receiver` can detect that the corresponding `Sender`s are dropped, I found the following behavior demonstrated by the program below.

```rust
use std::error::Error;
use tokio::sync::watch;

fn new_watch<T: Clone>(initial: T)
-> Result<(watch::Sender<T>, watch::Receiver<T>), watch::error::SendError<T>> {
    let (tx, rx) = watch::channel(initial.clone());
    let () = tx.send(initial)?;
    Ok((tx, rx))
}

async fn has_changed() -> Result<(), Box<dyn Error>> {
    let (_tx, rx) = new_watch(()).map_err(Box::new)?;
    rx.has_changed().map_err(Box::new)?;
    Ok(())
}

async fn drop_sender_then_has_changed() -> Result<(), Box<dyn Error>> {
    let rx = new_watch(()).map_err(Box::new)?.1;
    rx.has_changed().map_err(Box::new)?;
    Ok(())
}

async fn drop_sender_then_changed() -> Result<(), Box<dyn Error>> {
    let mut rx = new_watch(()).map_err(Box::new)?.1;
    rx.changed().await.map_err(Box::new)?;
    Ok(())
}

#[tokio::main]
async fn main() {
    eprintln!("has_changed: {:?}", has_changed().await);
    eprintln!(
        "drop_sender_then_has_changed: {:?}",
        drop_sender_then_has_changed().await,
    );
    eprintln!(
        "drop_sender_then_changed: {:?}",
        drop_sender_then_changed().await,
    );
}
```

`drop_sender_then_has_changed` returns an error. The specification of [`watch::Receiver::has_changed`](https://docs.rs/tokio/latest/tokio/sync/watch/struct.Receiver.html#method.has_changed) says,

> Returns an error if the channel has been closed.

However, not all receivers have been dropped. It's likely that the fact that all senders have been dropped is responsible for the error because my `has_changed` does not return an error.

The specification of [`watch::Receiver::changed`](https://docs.rs/tokio/latest/tokio/sync/watch/struct.Receiver.html#method.changed) says,

> This method returns an error if and only if the `Sender` is dropped.

All senders have been dropped, yet `drop_sender_then_changed` does not return an error.

Personally, I think that neither `has_changed` nor `changed` should return an error. If you allow for two `Sender`s, why wouldn't you allow for zero `Sender`s?

P.S. I suggest that you move the definition of “closed channel” to the top-level page instead of copying it to methods (such as [`watch::Sender::is_closed`](https://docs.rs/tokio/latest/tokio/sync/watch/struct.Sender.html#method.is_closed) and [`watch::Sender::send`](https://docs.rs/tokio/latest/tokio/sync/watch/struct.Sender.html#method.send)).

### PR DESCRIPTION
**Pull request by DSharifi**
## Motivation
Closes #7281 and supersedes #7556.

`changed` has a documentation bug: its docs claimed it would error if and only if the channel was closed, but the implementation only returns an error when the channel is closed AND there are no unseen values.

## Solution
-  The documentation on fallibility of `changed` has been updated to reflect its implementation.
- `has_changed`'s documentation has been updated to better highlight its difference with `changed`, as these methods fail on different conditions.
- The `watch` module documentation has been updated to reflect the difference between `changed` and `has_changed`.
- Integration tests have been added to test the intended behavior of `changed` and `has_changed` for closed channels.

### CODE REVIEW

**Comment by Darksonn** [comment]
Honestly, I'm somewhat concerned about this. Yes, the watch channel is kind of broken, but it's also used widely and I think lots of people out there rely on all sorts quirks of its behavior. I'm wary of changing it.

**Comment by ADD-SP** [comment]
@Darksonn 's concern is valid. At least, we can just fix the incorrect document of `changed`.

**Comment by DSharifi** [comment]
Thanks for the feedback @Darksonn. I understand the concern about breaking changes if downstream users depend on quirks of the watch API.

I'm on the fence if it's a change that is likely of breaking downstream users:
1. `has_changed` erroring on unseen values while `changed` doesn't creates an inconsistent API that might cause confusion and bugs.
2. For a user to break on the change of `has_changed` erroring for unseen values, they would need to be calling `has_changed` repeatedly without ever calling methods that mark values as seen. Effectively using `has_changed` as a sync check to see if the channel is closed without ever marking values as seen. I do see that we don't have any sync method, for example `closed`, to explicitly check for channel closures synchronously.

If we're still concerned about breaking the above use case, I'm happy to revise the PR and only keep the documentation fix and regression tests.

**Comment by ADD-SP** [comment]
This is precisely why I'm so cautious about adding new features to `tokio` crate, the bar of changing/fixing the behavior of `tokio` is significantly higher than `tokio-util`.

**Comment by ADD-SP** [comment]
Given that behavioral changes in tokio is always sensitive, I recommend the following approach. I prioritize backward compatibility and documentation clarity, even if it deviates from ideal principles of interface design.

- The existing functionality of `has_changed` should remain unchanged.
- The document of `changed` should be fixed to reflect the existing behavior.
- Highlight different behavior between the `has_changed` and `changed`.

Here are my rationales

-  The `has_changed` currently works as documented. More importantly, downstream may already rely on this specific behavior to detect the closed sender. While this is not a reasonable use case from my perspective, no dedicated method is available even for now, so changing this behavior now would likely introduce breaking changes for them.
-  The current documentation makes it difficult to quickly distinguish between these two methods. We should high light it to help downstream use these interfaces correctly.

**Comment by ADD-SP** [comment]
Hi @DSharifi , are you still working on this PR?

**Comment by DSharifi** [comment]
> Hi @DSharifi , are you still working on this PR?

Hey @ADD-SP, been a bit busy last week.

I'll update the PR tonight by reverting the behavioral changes, and instead update the documentation like you and @Darksonn suggested in the comments.

File: tokio/src/sync/watch.rs [hunk 1]
```diff
@@ -42,7 +44,27 @@
 //!   The current value at the time the [`Receiver`] is created is considered
 //!   *seen*.
 //!
-//! ## `borrow_and_update` versus `borrow`
+//! ## [`changed`] versus [`has_changed`]
```
Comment (ADD-SP) [inline tokio/src/sync/watch.rs:47]:
```suggestion
//! ## [`changed`] versus [`has_changed`]

```

File: tokio/src/sync/watch.rs [hunk 2]
```diff
@@ -42,7 +44,27 @@
...
+//!   value is seen or not and returns a boolean. This method does __not__ mark the
+//!   value as seen.
+//!
+//! * [`changed`] is an *asynchronous* method that will return once an unseen
+//!   value is in the channel. This method does mark the value as seen.
+//!
+//! Note there are two behavioral differences on when these two methods return
+//! an error.
+//!
+//! - [`has_changed`] errors if and only if the channel is closed.
```
Comment (ADD-SP) [inline tokio/src/sync/watch.rs:62]:
```suggestion
//! - [`has_changed`] errors as long as the  channel is closed.
```

File: tokio/src/sync/watch.rs [hunk 3]
```diff
@@ -637,15 +687,19 @@ impl<T> Receiver<T> {
...
+    /// Although this method is called `has_changed`, it does not check
+    /// messages for equality, so this call will return true even if the current
+    /// message is equal to the previous message.
+    ///
+    /// # Errors
     ///
-    /// Although this method is called `has_changed`, it does not check new
-    /// messages for equality, so this call will return true even if the new
-    /// message is equal to the old message.
+    /// Returns a [`RecvError`](error::RecvError) if and only if the channel has been closed.
```
Comment (ADD-SP) [inline tokio/src/sync/watch.rs:699]:
```suggestion
    /// Returns a [`RecvError`](error::RecvError) as long as the channel has been closed.
```

File: tokio/src/sync/watch.rs [hunk 4]
```diff
@@ -637,15 +687,19 @@ impl<T> Receiver<T> {
...
     ///
-    /// Returns an error if the channel has been closed.
     /// # Examples
     ///
+    /// ## Basic usage
```
Comment (ADD-SP) [inline tokio/src/sync/watch.rs:703]:
```suggestion
    /// ## Basic usage

```

File: tokio/src/sync/watch.rs [hunk 5]
```diff
@@ -660,9 +714,21 @@ impl<T> Receiver<T> {
     ///
     ///     // The value has been marked as seen
     ///     assert!(!rx.has_changed().unwrap());
+    /// }
+    /// ```
+    ///
+    /// ## Closed channel example
```
Comment (ADD-SP) [inline tokio/src/sync/watch.rs:722]:
```suggestion
    /// ## Closed channel example

```

File: tokio/tests/sync_watch.rs [hunk 6]
```diff
@@ -450,3 +450,56 @@ async fn sender_closed_is_cooperative() {
...
+#[tokio::test]
+async fn changed_succeeds_on_closed_channel_with_unseen_value() {
+    let (tx, mut rx) = watch::channel("A");
+    tx.send("B").unwrap();
+
+    drop(tx);
+
+    rx.changed()
+        .await
+        .expect("`changed` call does not return an error if the last value is not seen.");
```
Comment (ADD-SP) [inline tokio/tests/sync_watch.rs]:
```suggestion
        .expect("should not return error as long as the current value is not seen");
```

File: tokio/tests/sync_watch.rs [hunk 7]
```diff
@@ -450,3 +450,56 @@ async fn sender_closed_is_cooperative() {
...
+
+#[test]
+fn has_changed_errors_on_closed_channel_with_unseen_value() {
+    let (tx, rx) = watch::channel("A");
+    tx.send("B").unwrap();
+
+    drop(tx);
+
+    rx.has_changed()
+        .expect_err("`has_changed` iff channel is closed.");
```
Comment (ADD-SP) [inline tokio/tests/sync_watch.rs]:
```suggestion
        .expect_err("`has_changed` should return error as long as the channel is closed.");
```

File: tokio/tests/sync_watch.rs [hunk 8]
```diff
@@ -450,3 +450,56 @@ async fn sender_closed_is_cooperative() {
...
+}
+
+#[test]
+fn has_changed_errors_on_closed_channel_with_seen_value() {
+    let (tx, rx) = watch::channel("A");
+    drop(tx);
+
+    rx.has_changed()
+        .expect_err("`has_changed` call returns an error if the last value is seen.");
```
Comment (ADD-SP) [inline tokio/tests/sync_watch.rs]:
```suggestion
        .expect_err("`has_changed` should return an error if the last value is seen.");
```

File: tokio/tests/sync_watch.rs [hunk 9]
```diff
@@ -450,3 +450,56 @@ async fn sender_closed_is_cooperative() {
...
+}
+
+#[tokio::test]
+async fn changed_errors_on_closed_channel_with_seen_value() {
+    let (tx, mut rx) = watch::channel("A");
+    drop(tx);
+
+    rx.changed()
+        .await
+        .expect_err("`has_changed` iff channel is closed.");
```
Comment (ADD-SP) [inline tokio/tests/sync_watch.rs]:
```suggestion
        .expect_err("should return error if the tx is closed and the current value is seen");
```

File: tokio/src/sync/watch.rs (hunk 2 above)
Comment (DSharifi) [reply tokio/src/sync/watch.rs:62]: If the channel is closed, meaning all senders were dropped, then it can never be re-opened again. I.e. there are no methods to re-construct a `Sender` if we only have `Receiver`s alive.

With that context I don't think "as long as" is a good way to word it, since it can imply that the channel can be re-opened again, which is not the case.

File: tokio/src/sync/watch.rs (hunk 3 above)
Comment (DSharifi) [reply tokio/src/sync/watch.rs:699]: See: https://github.com/tokio-rs/tokio/pull/7584/files#r2365621553

File: tokio/src/sync/watch.rs (hunk 2 above)
Comment (DSharifi) [reply tokio/src/sync/watch.rs:62]: If we want to avoid using "if and only if" we can also go with using "when", but I find the language to be less ~~accurate/specific~~ precise.
```suggestion
//! - [`has_changed`] errors when the channel is closed.
```

Comment (ADD-SP) [reply tokio/src/sync/watch.rs:62]: I agree with "when" instead of "as long as", feel free to change it.

File: tokio/tests/sync_watch.rs (hunk 7 above)
Comment (DSharifi) [reply tokio/tests/sync_watch.rs]: https://github.com/tokio-rs/tokio/pull/7584/commits/8b8e4780dd0dbe497cc414c99c032301cdbb7d35

File: tokio/tests/sync_watch.rs (hunk 8 above)
Comment (DSharifi) [reply tokio/tests/sync_watch.rs]: https://github.com/tokio-rs/tokio/pull/7584/commits/8b8e4780dd0dbe497cc414c99c032301cdbb7d35

File: tokio/src/sync/watch.rs (hunk 2 above)
Comment (DSharifi) [reply tokio/src/sync/watch.rs:62]: Okay, so if I understand you correctly. You prefer to avoid using "if and only if" in the docs? I find it much more accurate, and it is already used several places in the tokio docs including current docs of `changed` (the bug in the documentation).


Just let me know and I'll update the docs + test expectation messages.

Comment (ADD-SP) [reply tokio/src/sync/watch.rs:62]: Emm, sorry, my mind was messy previously, I confused the `has_changed` and `changed`. I think "if and only if" is better.

Comment (DSharifi) [reply tokio/src/sync/watch.rs:62]: Nice.

FWIW, undoing the implementation changes and rewriting the docs was also confusing to remember which method errors on iff, and which must have the and condition.
