### PR TITLE
task: fix infinite loop when dropping a `LocalSet`

### LINKED ISSUE #1885: Infinite loop in LocalSet drop impl
## Version

```
cargo tree | grep tokio
└── tokio v0.2.2
```

## Platform

```
uname -a
Darwin tw-mbp-slynch 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
```

```
rustc --version
rustc 1.39.0 (4560ea788 2019-11-04
```

## Description

The following program enters an infinite loop within the `LocalSet` drop impl. I'd expect this not to happen and the program to exit normally.

This issue appears to be specific to `LocalSet` and also requires that the `Sender` part of the channel be dropped before the `Reciever`.
```rust
use std::io::Result;
use std::time::Duration;

use tokio::runtime::Builder;
use tokio::task::LocalSet;
use tokio::time::delay_for;

fn main() -> Result<()> {
    let (send, mut recv) = tokio::sync::mpsc::channel::<()>(1024);

    let mut rt = Builder::new()
        .enable_time()
        .basic_scheduler()
        .build()?;

    let workers = LocalSet::new();
    workers.spawn_local(async move {
        while let Some(_) = recv.recv().await {}
    });
    workers.block_on(&mut rt, async {
        delay_for(Duration::from_secs(1)).await;
    });

    drop(send);

    // This enters an infinite loop
    drop(workers);

    Ok(())
}
```

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "mcve"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2.2", features = [ "sync", "time", "rt-util", "rt-core" ] }
```
</details>

### PR DESCRIPTION
**Pull request by hawkw**
## Motivation

There's currently an issue in `task::LocalSet` where dropping the local
set can result in an infinite loop if a task running in the local set is
notified from outside the local set (e.g. by a timer). This was reported
in issue #1885.

This issue exists because the `Drop` impl for `task::local::Scheduler`
does not drain the queue of tasks notified externally, the way the basic
scheduler does. Instead, only the local queue is drained, leaving some
tasks in place. Since these tasks are never removed, the loop that
continues trying to cancel tasks until the owned task list is totally
empty continues infinitely.

I think this issue was due to the `Drop` impl being written before a
remote queue was added to the local scheduler, and the need to close the
remote queue as well was overlooked.

## Solution

This branch solves the problem by clearing the local scheduler's remote
queue as well as the local one.

I've added a test that reproduces the behavior. The test fails on master
and passes after this change.

In addition, this branch factors out the common task queue logic in the
basic scheduler runtime and the `LocalSet` struct in `tokio::task`. This
is because as more work was done on the `LocalSet`, it has gotten closer
and closer to the basic scheduler in behavior, and factoring out the
shared code reduces the risk of errors caused by `LocalSet` not doing
something that the basic scheduler does. The queues are now encapsulated
by a `MpscQueues` struct in `tokio::task::queue` (crate-public).  As a
follow-up, I'd also like to look into changing this type to use the same
remote queue type as the threadpool (a linked list).

In particular, I noticed the basic scheduler has a flag that indicates
the remote queue has been closed, which is set when dropping the
scheduler. This prevents tasks from being added after the scheduler has
started shutting down, stopping a potential task leak. Rather than
duplicating this code in `LocalSet`, I thought it was probably better to
factor it out into a shared type.

There are a few cases where there are small differences in behavior,
though, so there is still a need for separate types implemented _using_
the new `MpscQueues` struct. However, it should cover most of the 
identical code.

Note that this diff is rather large, due to the refactoring. However, the
actual fix for the infinite loop is very simple. It can be reviewed on its own
by looking at commit 4f46ac6. The refactor is in a separate commit, with
the SHA 90b5b1f.

Fixes #1885

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

File: tokio/src/runtime/basic_scheduler.rs [hunk 1]
```diff
@@ -188,7 +178,9 @@ where
                 scheduler.tick(local);
 
                 // Maintenance work
-                scheduler.drain_pending_drop();
+                unsafe {
```
Comment (jonhoo) [inline tokio/src/runtime/basic_scheduler.rs]: I love that these methods are now marked as `unsafe`. However, I _would_ then also like to see a comment on each added `unsafe` call to those methods arguing why the caller upholds the necessary safety invariants.

File: tokio/src/runtime/basic_scheduler.rs [hunk 2]
```diff
@@ -216,6 +208,221 @@ impl Spawner {
...
+
+impl<S> RemoteQueue<S>
+where
+    S: Schedule,
+{
+    /// Schedule a remote task.
+    ///
+    /// If the queue is open to accept new tasks, the task is pushed to the back
+    /// of the queue. Otherwise, if the queue is closed (the scheduler is
+    /// shutting down), the new task
```
Comment (jonhoo) [inline tokio/src/runtime/basic_scheduler.rs]: A weird text wrap here.

File: tokio/src/runtime/mod.rs [hunk 3]
```diff
@@ -183,7 +183,7 @@
 mod tests;
 
 cfg_rt_core! {
-    mod basic_scheduler;
+    pub(crate) mod basic_scheduler;
```
Comment (jonhoo) [inline tokio/src/runtime/mod.rs]: I think this suggests that the `Queue` type should be moved out of `basic_scheduler` now that it's shared.

Comment (hawkw) [reply tokio/src/runtime/mod.rs]: I thought leaving it here kind of gave the implication that the `LocalSet` was "reusing" code from `basic_scheduler`, which seemed right to me? But I can move it if you'd prefer.

File: tokio/src/task/local.rs [hunk 4]
```diff
@@ -416,88 +385,52 @@ impl Scheduler {
...
+        unsafe {
+            self.queues.drain_pending_drop();
+        }
 
         // Wait until all tasks have been released.
         // XXX: this is a busy loop, but we don't really have any way to park
         // the thread here?
-        while unsafe { !(*self.tasks.get()).is_empty() } {
-            self.drain_pending_drop();
+        unsafe {
```
Comment (jonhoo) [inline tokio/src/task/local.rs]: Hmm, what `Unpark` do the tasks use though? Could we not `Park` on that? Or do we not have one?

File: tokio/src/runtime/mod.rs (hunk 3 above)
Comment (jonhoo) [reply tokio/src/runtime/mod.rs]: Yeah, I can see that too. I just think that with this refactor arguably `Queues` is its own primitive that both `basic_scheduler` *and* `LocalSet` are using. Moving it out makes `Queues` more clearly "its own thing".

File: tokio/src/runtime/basic_scheduler.rs (hunk 1 above)
Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: added in 7d78ba66863e737fbb7009866c35e638e9251774, thanks for pointing that out!

File: tokio/src/runtime/mod.rs (hunk 3 above)
Comment (hawkw) [reply tokio/src/runtime/mod.rs]: hmm, I don't have a strong opinion on this, so I'd be fine with moving it out. What module would you put it in? The `Queues` type is specifically for a _single-threaded_ scheduler, so the module it goes in shouldn't have a name that implies the thread pool also uses this...

File: tokio/src/task/local.rs (hunk 4 above)
Comment (hawkw) [reply tokio/src/task/local.rs]: The local scheduler has an `AtomicWaker`
https://github.com/tokio-rs/tokio/blob/7d78ba66863e737fbb7009866c35e638e9251774/tokio/src/task/local.rs#L90-L92
that's set from the context every time the `LocalFuture` is polled:
https://github.com/tokio-rs/tokio/blob/7d78ba66863e737fbb7009866c35e638e9251774/tokio/src/task/local.rs#L306

I don't think it's okay to use that while we're dropping, though?

File: tokio/src/runtime/basic_scheduler.rs [hunk 5]
```diff
@@ -472,6 +482,8 @@ impl SchedulerPriv {
 impl Schedule for SchedulerPriv {
     fn bind(&self, task: &Task<Self>) {
         unsafe {
+            // safety: tasks are only bound to a basic scheduler from the local
+            // thread it runs on, so it's safe to call this.
```
Comment (jonhoo) [inline tokio/src/runtime/basic_scheduler.rs]: How are we guaranteed to be on the same thread? Is `SchedulerPriv` not `Sync`/`Send`?

File: tokio/src/runtime/basic_scheduler.rs [hunk 6]
```diff
@@ -482,6 +494,8 @@ impl Schedule for SchedulerPriv {
 
     fn release_local(&self, task: &Task<Self>) {
         unsafe {
+            // safety: Scheduler::release_local is only called from the
+            // scheduler's thread.
```
Comment (jonhoo) [inline tokio/src/runtime/basic_scheduler.rs]: How are we guaranteed to be on the same thread? Is `SchedulerPriv` not `Sync`/`Send`?

File: tokio/src/runtime/basic_scheduler.rs [hunk 7]
```diff
@@ -518,12 +537,14 @@ where
             task.shutdown();
         }
 
-        // Release owned tasks
         unsafe {
+            // safety: the basic scheduler's local state will not be accessed
+            // from another thread. Since dropping the scheduler closes the
+            // remote queue, no tasks will be notified externally.
```
Comment (jonhoo) [inline tokio/src/runtime/basic_scheduler.rs]: I'm not sure I follow this comment?

File: tokio/src/runtime/basic_scheduler.rs (hunk 6 above)
Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: The `release_local` method is only _called_ from the same thread as the scheduler — it's part of the `Schedule` trait's contract.

File: tokio/src/runtime/mod.rs (hunk 3 above)
Comment (jonhoo) [reply tokio/src/runtime/mod.rs]: `mod task_queue`? Is there a particular reason why we can't also share the queue impl that the thread pool uses? It also has a notion of local and remote tasks, right?

File: tokio/src/task/local.rs (hunk 4 above)
Comment (jonhoo) [reply tokio/src/task/local.rs]: Not sure -- you'd have to check with @carllerche

File: tokio/src/runtime/basic_scheduler.rs (hunk 6 above)
Comment (jonhoo) [reply tokio/src/runtime/basic_scheduler.rs]: Ah, okay, then it'd be good to include that in the comment.

File: tokio/src/runtime/basic_scheduler.rs (hunk 5 above)
Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: `bind` is only called when we poll a task for the first time. this only happens when the basic scheduler is running, and all the tasks are polled from one thread.

Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: Hopefully this is clearer in https://github.com/tokio-rs/tokio/pull/1892/commits/03357f1b78744fd4bf3f963859f8573c22b25d6e?

File: tokio/src/runtime/basic_scheduler.rs (hunk 6 above)
Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: reworded in https://github.com/tokio-rs/tokio/pull/1892/commits/03357f1b78744fd4bf3f963859f8573c22b25d6e

File: tokio/src/runtime/basic_scheduler.rs (hunk 7 above)
Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: reworded in https://github.com/tokio-rs/tokio/pull/1892/commits/03357f1b78744fd4bf3f963859f8573c22b25d6e, hopefully it's clearer now?

File: tokio/src/runtime/mod.rs (hunk 3 above)
Comment (hawkw) [reply tokio/src/runtime/mod.rs]: > Is there a particular reason why we can't also share the queue impl that the thread pool uses? It also has a notion of local and remote tasks, right?

Yes, but it's significantly different. In order to implement work stealing, the threadpool workers need to allow other workers to steal tasks from their queues. This necessitates some complicated lock-free structures. In the local set and basic scheduler cases, there are fewer synchronization points. Carl might be able to better describe the differences, but this code is not really shared with the threadpool.

File: tokio/src/runtime/basic_scheduler.rs [hunk 8]
```diff
@@ -216,6 +210,220 @@ impl Spawner {
...
+    /// Push a task to the local queue.
+    ///
+    /// # Safety
+    ///
+    /// This *must* be called only from the thread that owns the scheduler.
+    pub(crate) unsafe fn push_local(&self, task: Task<S>) {
+        (*self.local_queue.get()).push_back(task);
+    }
+
+    /// Push a task to the local queue.
```
Comment (kleimkuhler) [inline tokio/src/runtime/basic_scheduler.rs]: Release a task from the local queue!

File: tokio/src/task/local.rs [hunk 9]
```diff
@@ -416,88 +389,58 @@ impl Scheduler {
...
 }
 
 impl Drop for Scheduler {
     fn drop(&mut self) {
+        // Close the remote queue
+        self.queues.close_remote();
+
         // Drain all local tasks
-        while let Some(task) = self.next_local_task() {
+        while let Some(task) = unsafe { self.queues.next_local_task() } {
```
Comment (kleimkuhler) [inline tokio/src/task/local.rs]: It looks like draining local tasks on `Scheduler` is the same as `BasicScheduler`. Maybe a default `close_local` method could be added to `Queues` similar to `close_remote`?

File: tokio/src/task/local.rs [hunk 10]
```diff
@@ -416,88 +389,58 @@ impl Scheduler {
...
-        // XXX: this is a busy loop, but we don't really have any way to park
-        // the thread here?
-        while unsafe { !(*self.tasks.get()).is_empty() } {
-            self.drain_pending_drop();
+            self.queues.drain_pending_drop();
+
+            // Wait until all tasks have been released.
+            // XXX: this is a busy loop, but we don't really have any way to park
+            // the thread here?
+            while self.queues.has_tasks_remaining() {
```
Comment (carllerche) [inline tokio/src/task/local.rs]: tbh, i don't really know if this can happen. I believe the loop was copied from the threaded scheduler where a task could be "stolen" and running on a different thread and that thread has a "lock" on the task... anyway, not a big deal for now, but we should investigate it and better document the guarantees of `task` (it was initially not _really_ for reusing).

File: tokio/src/runtime/basic_scheduler.rs [hunk 11]
```diff
@@ -266,63 +474,51 @@ impl SchedulerPriv {
...
     fn bind(&self, task: &Task<Self>) {
         unsafe {
-            (*self.owned_tasks.get()).insert(task);
+            // safety: `Queues::add_task` is only safe to call from the thread
+            // that owns the queues (the thread the scheduler is running on).
+            // `Scheduler::bind` is called when polling a task that
+            // doesn't have a scheduler set. We will only poll tasks from the
+            // thread that the scheduler is running on. Therefore, this is safe
+            // to call.
+            self.queues.add_task(task);
```
Comment (carllerche) [inline tokio/src/runtime/basic_scheduler.rs]: We don't have great terminology for this action. "bind" / "add_task" / ....

Nothing to do now, but maybe ponder how we can rename `bind` or describe it better.

File: tokio/src/runtime/basic_scheduler.rs [hunk 12]
```diff
@@ -266,63 +474,51 @@ impl SchedulerPriv {
...
+            // `release` rather than `release_local`.
+            self.queues.release_local(task);
         }
     }
 
     fn schedule(&self, task: Task<Self>) {
-        let is_current = ACTIVE.with(|cell| {
-            cell.get() == self as *const SchedulerPriv
-        });
+        let is_current = ACTIVE.with(|cell| cell.get() == self as *const SchedulerPriv);
```
Comment (carllerche) [inline tokio/src/runtime/basic_scheduler.rs]: The `ACTIVE` thing was hacked in to fix a bug. Nothing to do now, but we probably should try cleaning it up sometime...

File: tokio/src/runtime/mod.rs (hunk 3 above)
Comment (jonhoo) [reply tokio/src/runtime/mod.rs]: Ah, yes, of course, you're right. How about `mpsc_task_queue`?

File: tokio/src/runtime/basic_scheduler.rs [hunk 13]
```diff
@@ -482,8 +482,12 @@ impl SchedulerPriv {
 impl Schedule for SchedulerPriv {
     fn bind(&self, task: &Task<Self>) {
         unsafe {
-            // safety: tasks are only bound to a basic scheduler from the local
-            // thread it runs on, so it's safe to call this.
+            // safety: `Queues::add_task` is only safe to call from the thread
+            // that owns the queues (the thread the scheduler is running on).
+            // `Scheduler::bind` is called when polling a task that
+            // doesn't have a scheduler set. We will only poll tasks from the
```
Comment (jonhoo) [inline tokio/src/runtime/basic_scheduler.rs]: Should this say "We will only poll **new** tasks from the" ?

File: tokio/src/runtime/basic_scheduler.rs (hunk 11 above)
Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: I thought about calling the method `Queues::bind` as well, but I thought it seemed a little weird to have a `Schedule::bind` that basically just made an assertion and then called `Queues::bind`.

FWIW, I am somewhat in favour of renaming the `Schedule` method for the reason that a search for `bind` in tokio also turns up a bunch of socket methods. Not a _big_ deal though.

Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: Also: documenting when and where the different `Schedule` methods are called would be really helpful — I think I have a good handle on it now, but it was confusing early on, and it would be nice to have something to refer to in reviews. I might try to do that in a follow-up.

File: tokio/src/runtime/basic_scheduler.rs (hunk 8 above)
Comment (hawkw) [reply tokio/src/runtime/basic_scheduler.rs]: fixed in a01f5963215178b2a9042b996fe99e8a18987fe3, thanks for spotting!

File: tokio/src/task/local.rs (hunk 9 above)
Comment (hawkw) [reply tokio/src/task/local.rs]: yup, I added it in a01f5963215178b2a9042b996fe99e8a18987fe3. but, I also realized that only the loop that drains remaining owned tasks is different between the local set and basic scheduler, so i put all the other fns in a single `fn shutdown`.

File: tokio/src/runtime/mod.rs (hunk 3 above)
Comment (hawkw) [reply tokio/src/runtime/mod.rs]: I moved the queues to their own module (`task::queue`) in fa878c6aa5cf31770e1d2a4a6270f029774aa570, and renamed the struct to `SingleThreadQueues`, which I didn't really like...`mpsc` seems neater, thanks!

Comment (jonhoo) [reply tokio/src/runtime/mod.rs]: :+1: I think this `pub(crate)` modifier can then be removed again, right?

Comment (hawkw) [reply tokio/src/runtime/mod.rs]: yup, good eye! i missed that!
