### PR TITLE
Fix clippy errors

### LINKED ISSUE #2251: select! with one branch causes a clippy error
## Version

`cargo tree | grep tokio`:

```
└── tokio v0.2.11
    └── tokio-macros v0.2.4
```

## Platform

Darwin MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro13,2 Darwin

## Description

Using the `select!` macro with only a single branch causes the following clippy error:

```
error: any number modulo 1 will be 0
  --> src/supervisor.rs:23:9
   |
23 | /         select! {
24 | |             res = zombies.reap().fuse() =>{
25 | |                 let pid = res?;
26 | |                 info!("reaped child"; "pid" => pid.as_raw())
27 | |             }
28 | |         };
   | |__________^
   |
   = note: `#[deny(clippy::modulo_one)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#modulo_one
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

This is unlikely to bit anyone using the macro for real, but it should be possible to add a `#[allow(clippy:modulo_one)]` to the offending bit - I think it's [this one](https://github.com/tokio-rs/tokio/blob/master/tokio/src/macros/select.rs#L362).

### PR DESCRIPTION
**Pull request by MikailBag**
## Motivation

Fixes #2251

## Solution
Add `#[allow(clippy::modulo_one)]` on the statement in question.

### CODE REVIEW

**Comment by MikailBag** [comment]
CI failure: https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=5990&view=logs&j=edbb8bb1-bc6c-5b89-6b1a-b043f7e49efc&t=759fbeb1-c67f-5939-907c-b2711d9a157b&l=1329
does not seem related to this PR.

File: tokio/src/macros/select.rs [hunk 1]
```diff
@@ -359,8 +359,11 @@ macro_rules! select {
                 let start = $crate::macros::support::thread_rng_n(BRANCHES);
 
                 for i in 0..BRANCHES {
-                    let branch = (start + i) % BRANCHES;
-
+                    let branch;
+                    #[allow(clippy::modulo_one)]
+                    {
+                        branch = (start + i) % BRANCHES
```
Comment (Darksonn) [inline tokio/src/macros/select.rs:365]: I can't help but feel that this is missing a semicolon.
