### PR TITLE
process: add example for reading `Child` stdout

### LINKED ISSUE #7138: process: document how to read output from `Child`
tokio v1.41.0
ubuntu linux 22.04

**Description**

Child::wait_with_output() should take `&mut self` instead of `self`.    Taking `self` means it cannot be used in a `select!()`, which means there is no good way to simultaneously wait for a child processes output and a kill/cancel channel message.

stated differently, the docs for Child::kill() provide an example of using `select!()` with branches for Child::wait() and a oneshot channel recv().  This example works perfectly for Child::wait() but fails to compile for Child::wait_with_output().

The only way I was able to get it to work was to copy/paste the impl of Child::wait_with_output() into my own code and modify it to take `&mut self` instead.

See discussion #7132 with playground examples.

### PR DESCRIPTION
**Pull request by maminrayej**
Resolves #7138.

### CODE REVIEW

File: tokio/src/process/mod.rs [hunk 1]
```diff
@@ -1190,6 +1192,41 @@ impl Child {
...
+    ///     let mut buff = Vec::new();
+    ///     let wait_for_output = join(child.wait(), stdout.read_to_end(&mut buff));
+    ///
+    ///     tokio::select! {
+    ///             _ = wait_for_output => {}
+    ///             _ = rx => child.kill().await.expect("kill failed"),
+    ///     }
+    ///
+    ///     assert_eq!(buff, b"Hello World!\n");
+    /// }
```
Comment (Darksonn) [inline tokio/src/process/mod.rs:1228]: I think what I would recommend is that you read the output from a background task. Something along these lines:
```rs
let stdout_task = tokio::spawn(async { /* read stdout here */ });
tokio::select! {
     _ = child.wait() => {},
     _ = kill_signal => child.kill.await?,
};
let output = stdout_task.await?;
```

File: tokio/src/process/mod.rs [hunk 2]
```diff
@@ -1190,6 +1192,46 @@ impl Child {
...
+    ///         let mut buff = Vec::new();
+    ///         let _ = stdout.read_to_end(&mut buff).await;
+    ///
+    ///         buff
+    ///     });
+    ///
+    ///     tokio::select! {
+    ///             _ = child.wait() => {}
+    ///             _ = rx => { child.kill().await.expect("kill failed") },
+    ///     }
```
Comment (mox692) [inline tokio/src/process/mod.rs:1228]: Style nit:

```suggestion
    ///     tokio::select! {
    ///         _ = child.wait() => {}
    ///         _ = rx => { child.kill().await.expect("kill failed") },
    ///     }
```

**Review by mox692 — APPROVED** [review]

File: tokio/src/process/mod.rs (hunk 2 above)
Comment (maminrayej) [reply tokio/src/process/mod.rs:1228]: Thanks.
