### PR TITLE
tcp: deprecate `TcpStream::try_clone()`

### LINKED ISSUE #774: Error : "socket already registered" when upgrading from 0.1.11 to 0.1.13
## Version
Working version (0.1.11) :
└── tokio v0.1.11
    ├── tokio-codec v0.1.1
    │   └── tokio-io v0.1.10
    ├── tokio-current-thread v0.1.4
    │   └── tokio-executor v0.1.5
    ├── tokio-executor v0.1.5 (*)
    ├── tokio-fs v0.1.4
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-threadpool v0.1.9
    │       └── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.10 (*)
    ├── tokio-io v0.1.10 (*)
    ├── tokio-reactor v0.1.7
    │   ├── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.10 (*)
    ├── tokio-tcp v0.1.2
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-reactor v0.1.7 (*)
    ├── tokio-threadpool v0.1.9 (*)
    ├── tokio-timer v0.2.8
    │   └── tokio-executor v0.1.5 (*)
    ├── tokio-udp v0.1.3
    │   ├── tokio-codec v0.1.1 (*)
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-reactor v0.1.7 (*)
    └── tokio-uds v0.2.4
        ├── tokio-codec v0.1.1 (*)
        ├── tokio-io v0.1.10 (*)
        └── tokio-reactor v0.1.7 (*)

Failing version (0.1.13) : 
└── tokio v0.1.13
    ├── tokio-codec v0.1.1
    │   └── tokio-io v0.1.10
    ├── tokio-current-thread v0.1.3
    │   └── tokio-executor v0.1.5
    ├── tokio-executor v0.1.5 (*)
    ├── tokio-fs v0.1.4
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-threadpool v0.1.8
    │       └── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.10 (*)
    ├── tokio-io v0.1.10 (*)
    ├── tokio-reactor v0.1.6
    │   ├── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.10 (*)
    ├── tokio-tcp v0.1.2
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-reactor v0.1.6 (*)
    ├── tokio-threadpool v0.1.8 (*)
    ├── tokio-timer v0.2.8
    │   └── tokio-executor v0.1.5 (*)
    ├── tokio-udp v0.1.2
    │   ├── tokio-codec v0.1.1 (*)
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-reactor v0.1.6 (*)
    └── tokio-uds v0.2.3
        ├── tokio-io v0.1.10 (*)
        └── tokio-reactor v0.1.6 (*)

## Platform

Linux Moi-arch 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux

## Description

When updating from tokio `0.1.11` to `0.1.13`, an io error appeared : `socket already registered`.
This appears when creating a new `Frame` on a `TcpStream` that already has a `Frame` attached to it.
For instance : I have a frame that listens to arriving packets and I want to create one to send messages.

I think this error comes from #660 : The new frame is registered in another reactor than the first one, thus creating the `already registered` error.

### PR DESCRIPTION
**Pull request by stjepang**
## Motivation

`TcpStream::clone()` creates a copy of a TCP stream that may be accidentally tied to a different reactor than the original. See [here](https://github.com/tokio-rs/tokio/issues/774#issuecomment-442632537) for a reproducible bug and [here](https://github.com/tokio-rs/tokio/issues/774#issuecomment-443519689) for a more elaborate explanation.

## Solution

Deprecate `TcpStream::try_clone()` and nudge users towards `TcpStream::split()` instead.

Closes #774.

### CODE REVIEW

**Comment by stjepang** [comment]
@carllerche In https://github.com/tokio-rs/tokio/issues/774#issuecomment-451059317, you said:

> the solution would be to deprecate try_clone and to update it to always return an error.

Do we really want to always return an error? I worry that this might break some otherwise working code. A deprecation warning should be enough, I think.

**Comment by carllerche** [comment]
You will have to merge master once #825 lands to fix the build.

**Comment by carllerche** [comment]
@stjepang it doesn't actually work as intended today, so any code that uses `try_clone` is probably already broken.

The issue is that each both stream handles will have separate `PollEvented` instances but epoll can only register a single token for both, so right now, there isn't any way to notify both stream handles.

In theory, it would be possible to make cloning work, but it would not be simple and add overhead to the non-cloned case. I'd rather better understand the use case for cloning here.

**Comment by stjepang** [comment]
Ok, I've turned `try_clone()` into an error.

Judging by https://github.com/guydunigo/tokio_test/blob/master/src/main.rs, I think @guydunigo wanted to have one task for writing into `TcpStream` and one task for reading from it. This is a use case where `split()` would be appropriate.

**Comment by carllerche** [comment]
Are there other try_clone fns to deprecate as well?

**Comment by stjepang** [comment]
There is also [`fs::File::poll_try_clone()`](https://docs.rs/tokio/0.1.13/tokio/fs/struct.File.html#method.poll_try_clone). Should we deprecated that one, too?

**Comment by stjepang** [comment]
@carllerche `File::poll_try_clone()` dups the fd, but the fd is not tied to a reactor (it uses `blocking()` instead), so it doesn't suffer from the same problem.

If we ever implement "real" async filesystem IO (e.g. with Linux AIO) and tie it to a reactor, then it will become a problem.

cc @LucioFranco Since you've been reviewing code involving this function, do you perhaps have an opinion?

**Comment by LucioFranco** [comment]
@stjepang I am indifferent to keeping it but if its going to cause issues later down the line I am fine with removing it. So I see how this might cause issues though with the reactor and how it may cause more confusion down the line. So 👍 on deprecating `File::poll_try_clone`.

File: tokio-tcp/src/stream.rs [hunk 1]
```diff
@@ -784,8 +784,11 @@ impl TcpStream {
     #[deprecated(since = "0.1.14", note = "use `split()` instead")]
     #[doc(hidden)]
     pub fn try_clone(&self) -> io::Result<TcpStream> {
-        let io = self.io.get_ref().try_clone()?;
-        Ok(TcpStream::new(io))
+        // Rationale for deprecation:
+        // - https://github.com/tokio-rs/tokio/pull/824
+        // - https://github.com/tokio-rs/tokio/issues/774#issuecomment-451059317
+        let msg = "`TcpStream::split()` is deprecated because it doesn't work as intended";
```
Comment (TheGr8Nik) [inline tokio-tcp/src/stream.rs]: I think the message should be `TcpStream::try_clone()` instead of `TcpStream::split()`

Comment (stjepang) [reply tokio-tcp/src/stream.rs]: This was eventually fixed: https://github.com/tokio-rs/tokio/blob/847fb59b17d8e9786abfdac474ad59e120a94254/tokio-tcp/src/stream.rs#L788
