### PR TITLE
runtime: fix lost wakeup bug in scheduler

### LINKED ISSUE #1768: Runtime gets stuck
## Version

current master branch (27e5b41067d01c0c9fac230c5addb58034201a63)

## Platform

Windows 10

## Description

The following program gets stuck in a release build. After some  amount of time, no more printouts will happen. This indicates that a wakeup got lost. I played a bit around, and discovered the following:
- The biggest difference lies within the value of `NR_ITERATIONS` - the smaller it is the faster it gets stuck. Maybe an issue with tasks joining "too early"?
- If the `task::spawn` is removed, everything looks fine
- Caught the issue in the debugger, but it only tells me one thread is waiting on `thread::park`, and others are waiting on IO completion ports
- The amount of runtime threads does not seem to make a difference. I just adjusted it to 1 to have less noise in the debugger.
- It does not seem to happen with the `current_thread` runtime

```rust
use tokio::sync::Mutex;
use tokio::sync::oneshot::channel;
use std::sync::Arc;

async fn do_iteration() {
    // Changing this to a higher value will prevent it from getting stuck
    const NR_ITERATIONS: usize = 5;
    let m = Arc::new(Mutex::new(()));//IntrusiveMutex::new((), true));
    let (sender, receiver) = channel();

    let m = m.clone();
    tokio::spawn(async move {
        for _ in 0..NR_ITERATIONS {
            let _ = m.lock().await;
        }
        sender.send(());
    });

    receiver.await;
}

fn main() {
    const NR_ITERATIONS: usize = 10000;
    const BLOCK_ON_PER_RT: usize = 3000;

    for i in 0 .. NR_ITERATIONS {
        {
            println!("Starting runtime {}", i);
            let mut builder = tokio::runtime::Builder::new();
            builder.thread_pool().num_threads(1);
            let mut rt = builder.build().unwrap();

            for _ in 0 .. BLOCK_ON_PER_RT {
                rt.block_on(async {
                    do_iteration().await;
                });
            }

            println!("Stopping runtime");
        }
        println!("Stopped runtime");
    }
}
````

### PR DESCRIPTION
**Pull request by carllerche**
When checking if a worker needs to be unparked, the SeqCst load does not
provide the necessary synchronization to ensure the scheduled task is
visible to the searching worker. The `load` is switched to
`fetch_add(0)` which does establish the necessary synchronization.

Adding unit tests catching this bug will require a fix to loom and will
be done at a later time. The bug fix has been validated with manual
testing.

Fixes #1768

### CODE REVIEW

File: tokio/src/runtime/thread_pool/queue/global.rs [hunk 1]
```diff
@@ -51,7 +51,7 @@ impl<T: 'static> Queue<T> {
     /// Close the worker queue
     pub(super) fn close(&self) -> bool {
         // Acquire the lock
-        let _p = self.pointers.lock().unwrap();
+        let p = self.pointers.lock().unwrap();
```
Comment (hawkw) [inline tokio/src/runtime/thread_pool/queue/global.rs]: Are the explicit drops part of the fix, or are they left over from debugging?

File: tokio/src/runtime/thread_pool/idle.rs [hunk 2]
```diff
@@ -89,22 +89,15 @@ impl Idle {
...
             return false;
         }
 
         // It is possible for this routine to allow more than 50% of the workers
         // to search. That is OK. Limiting searchers is only an optimization to
         // prevent too much contention.
-        //
-        // At this point, we do not need a hard synchronization with `notify_work`, so `AcqRel` is sufficient.
-        State::inc_num_searching(&self.state, AcqRel);
+        State::inc_num_searching(&self.state, SeqCst);
```
Comment (hawkw) [inline tokio/src/runtime/thread_pool/idle.rs]: Is changing these to `SeqCst` also part of the fix?

File: tokio/src/runtime/thread_pool/queue/global.rs (hunk 1 above)
Comment (carllerche) [reply tokio/src/runtime/thread_pool/queue/global.rs]: They are not part of the fix, but given that the mutex protects more than just the  data, I thought it would be good to be explicit.

File: tokio/src/runtime/thread_pool/idle.rs (hunk 2 above)
Comment (carllerche) [reply tokio/src/runtime/thread_pool/idle.rs]: Kind of... It's probably best to stick exclusively w/ SeqCst.
