### PR TITLE
mpsc: ensure try_reserve error is consistent with try_send

### LINKED ISSUE #4118: mpsc: `try_reserve()` gives `TrySendError::Full(())` for closed channel
**Version**
- `tokio v1.10.0`
- `tokio v1.11.0`
- `master @ f1b89675eb621edc23a9aa31d625270307fb6ce9`

**Platform**
`Linux symbiont 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description**

`try_reserve()` on `tokio::sync::mpsc::Sender` return `Err(TrySendError::Full(()))` instead of `Err(TrySendError::Closed(()))` when the channel is closed. See the following example code ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7cccd9dfb94592a5174b0eacb27fe494)):

```rust
use tokio::sync::mpsc::{self, error::TrySendError}; // 1.11.0

#[tokio::main]
async fn main() {
    let (tx, mut rx) = mpsc::channel::<u64>(1);
    
    // Just normal behaviour: can reserve a slot, use it to send, and now both
    // try_send() and try_reserve() see the channel buffer as full.
    assert_eq!(tx.is_closed(), false);
    assert!(matches!(tx.try_reserve(), Ok(_)));
    tx.send(123).await.unwrap();
    assert!(matches!(tx.try_send(456), Err(TrySendError::Full(_))));
    assert!(matches!(tx.try_reserve(), Err(TrySendError::Full(_))));
    
    // Still normal behaviour: consuming from the channel frees up a slot.
    let _ = rx.recv().await;
    assert!(matches!(tx.try_reserve(), Ok(_)));
    
    // However, when we close the channel by dropping the receiver...
    drop(rx);
    assert_eq!(tx.is_closed(), true);
    // ... try_send() gets the expected Closed error ...
    assert!(matches!(tx.try_send(456), Err(TrySendError::Closed(_))));
    // ... but try_reserve() doesn't, it gets Full instead!
    assert!(matches!(tx.try_reserve(), Err(TrySendError::Full(_))));
}
```

I would expect `try_reserve()` to return `Err(TrySendError::Closed(()))` in this situation, in line with `try_send(...)` behaviour and the documentation of `TrySendError`.

(This problem also applies to `try_reserve_owned()`.)

### PR DESCRIPTION
**Pull request by alanbriolat**
Fixes #4118.

## Motivation

`try_reserve()` and `try_reserve_owned()` of `tokio::sync::mpsc::Sender` are inconsistent with `try_send()` in the error they return, signalling `Full` instead of `Closed` for a closed channel. If other code relies on this error as documented, it might forever retry sending to a closed channel.

## Solution

I copied the handling of the `TryAcquireError` from `try_send()` to `try_reserve()` and `try_reserve_owned()`; as far as I can tell, this is probably what it should have been in the first place when `try_reserve()` was introduced by 672be92a03a489d028ed7ec2c6b1abdbf0874a1d, and then `try_reserve_owned()` just copied `try_reserve()` behaviour.

### CODE REVIEW

File: tokio/tests/sync_mpsc.rs [hunk 1]
```diff
@@ -418,9 +418,33 @@ fn dropping_rx_closes_channel_for_try() {
...
+        }
+    }
+
+    {
+        let err = assert_err!(tx.try_reserve_owned());
+        match err {
+            TrySendError::Closed(..) => {}
+            _ => panic!(),
+        }
+    }
```
Comment (Darksonn) [inline tokio/tests/sync_mpsc.rs:435]:
```suggestion
    assert!(matches(tx.try_reserve_owned(), Err(TrySendError::Closed(_))));
```

Comment (alanbriolat) [reply tokio/tests/sync_mpsc.rs:435]: I only did them this way to be consistent with the other assertion in this function without modifying the existing assertion. Should I just reformat all 3?

Comment (alanbriolat) [reply tokio/tests/sync_mpsc.rs]: OK, I just reformatted all 3, at which point they became an exact duplicate of the `try_reserve_on_closed_channel()` test I added, so I've removed that too.

Also remembered to run the formatter this time :facepalm:

**Review by Darksonn — APPROVED** [review]
Thanks!
