### PR TITLE
sync: fix slow receivers in broadcast

### LINKED ISSUE #2425: sync::broadcast returns Lagged error when capacity is not exceeded
## Version
rustc 1.41.0 (5e1a79984 2020-01-27)
tokio: 0.2.18

## Platform
Linux  5.3.0-45-generic #37~18.04.1-Ubuntu 

## Description
Hi! I ran into an issue on the sync::broadcast::channel where buffering events up to the channel's capacity triggers a `RecvError::Lagged` error when the channel is finally read from. I expected this error to only be triggered if the channel's capacity is exceeded.

As an example the following code errors out with `Err(Lagged(1))`.

```
#[tokio::main]
async fn main() {
    let (tx, mut rx) = tokio::sync::broadcast::channel(1);
    let _1 = tokio::spawn(async move {
        tx.send(0).unwrap();
    });
    let _2 = tokio::spawn(async move {
        rx.recv().await.unwrap(); // panic
    });
    _1.await.unwrap();
    _2.await.unwrap();
}

```

It seems to be a threading issue? compared to the following that works as expected.

```
#[tokio::main]
async fn main() {
    let (tx, mut rx) = tokio::sync::broadcast::channel(1);
    tx.send(0).unwrap();
    let _2 = tokio::spawn(async move {
        rx.recv().await.unwrap(); // OK
    });
    _2.await.unwrap();
}

```

### PR DESCRIPTION
**Pull request by kleimkuhler**
## Motivation

Broadcast uses a ring buffer to store values sent to the channel. In order to
deal with slow receivers, the oldest values are overwritten with new values
once the buffer wraps. A receiver should be able to calculate how many values
it has missed.

Additionally, when the broadcast closes, a final value of `None` is sent to
the channel. If the buffer has wrapped, this value overwrites the oldest
value.

This is an issue mainly in a single capacity broadcast when a value is sent
and then the sender is dropped. The original value is immediately overwritten
with `None` meaning that receivers assume they have lagged behind.

Closes #2425

## Solution

A value of `None` is no longer sent to the channel when the final sender has
been dropped. This solves the single capacity broadcast case by completely
removing the behavior of overwriting values when the channel is closed.

Now, when the final sender is dropped a closed bit is set on the next slot
that the channel is supposed to send to.

In the case of a fast receiver, if it finds a slot where the closed bit is
set, it knows the channel is closed without locking the tail.

In the case of a slow receiver, it must first find out if it has missed any
values. This is similar to before, but must be able to account for channel
closure.

If the channel is not closed, the oldest value may be located at index `n`. If
the channel is closed, the oldest value is located at index `n - 1`.

Knowing the index where the oldest value is located, a receiver can calculate
how many values it may have missed and starts to catch up.

Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

### CODE REVIEW

File: tokio/src/sync/broadcast.rs [hunk 1]
```diff
@@ -604,13 +614,20 @@ impl<T> Sender<T> {
...
+        } else {
+            slot.write.val.with_mut(|ptr| unsafe { *ptr = value });
+        }
 
         // Set remaining receivers
         slot.rem.store(rem, SeqCst);
 
         // Release the slot lock
-        slot.lock.store(0, SeqCst);
+        slot.lock.fetch_and(CLOSED, SeqCst);
```
Comment (carllerche) [inline tokio/src/sync/broadcast.rs:630]: Not a huge deal, but `store` is going to be a bit lighter than `fetch_and` (store vs. read-modify-write). Because the lock is held here, you should be able to replace this w/ `store(is_closed)` if you track whether or not the  channel is being closed.

Not a blocker, so up to you.

File: tokio/src/sync/broadcast.rs [hunk 2]
```diff
@@ -688,28 +705,48 @@ impl<T> Receiver<T> {
...
+            guard.drop_no_rem_dec();
+            self.next = next;
+
+            return Err(TryRecvError::Lagged(missed));
         }
 
         self.next = self.next.wrapping_add(1);
 
+        // If the `CLOSED` bit it set on the slot, the channel is closed
+        if slot.lock.load(SeqCst) & CLOSED == CLOSED {
```
Comment (carllerche) [inline tokio/src/sync/broadcast.rs:745]: **if** I'm reading this right, you should be able to read this when "locking" the slot (call to `try_rx_lock)`.

Again, not super critical at this point, but a comment saying "we _could_ do this" could be helpful for anyone working in this file later.

Comment (kleimkuhler) [reply tokio/src/sync/broadcast.rs:743]: Good call. I moved this to where we set the closed bit or write a new value

File: tokio/src/sync/broadcast.rs (hunk 1 above)
Comment (kleimkuhler) [reply tokio/src/sync/broadcast.rs]: Good call. I moved this to where we set the closed bit or write a new value

File: tokio/src/sync/broadcast.rs (hunk 2 above)
Comment (kleimkuhler) [reply tokio/src/sync/broadcast.rs:747]: I've added to the comment above. I have an idea for how this could happen, but it will require some additional changes to what `try_rx_lock` returns and how we properly spin when it's locked by a writer.

I started making the change as part of this, but will keep it separate since it is not really related to this fix.
