### PR TITLE
time: fix time::advance() with sub-ms durations

### LINKED ISSUE #3837: time::advance advances too far when given a Duration of sub-millisecond granularity
**Version**
```
tokio-repro v0.1.0 (/Users/hallmaxw/tokio-repro)
└── tokio v1.6.1
    └── tokio-macros v1.2.0 (proc-macro)
```

**Platform**
Darwin Kernel Version 19.6.0

**Description**

`time::advance` advances time too far when it's given a Duration of sub-millisecond granularity. This worked prior to this commit, which was included in tokio 1.6 https://github.com/tokio-rs/tokio/commit/2b9b55810847b4c7855e3de82f432ca997600f30

I assume this is happening because the above commit updates `time::advance` to use `sleep_until`, which operates at millisecond granularity.

Here's some code to reproduce the  issue:

```rust
#[cfg(test)]
mod tests {
    use std::time::Duration;

    use tokio::time::{self, Instant};

    #[tokio::test]
    async fn test_time_advance() {
        time::pause();
        let start_time = Instant::now();
        time::advance(Duration::from_micros(3_141_592)).await;

        // The duration elapsed is the duration passed to time::advance plus
        // an extra 1 ms. You'd expect the duration elapsed to just be the duration
        // passed to time::advance
        assert_eq!(
            start_time.elapsed(),
            Duration::from_micros(3_141_592 + 1_000)
        )
    }
}
```

I expected the duration elapsed to be the exact duration passed to `time::advance`.

Instead, the duration elapsed was the duration passed to `time::advance` plus an additional millisecond.

cc: @LucioFranco

### PR DESCRIPTION
**Pull request by carllerche**
Update the advance logic to factor in the timer's ms rounding.

Fixes #3837

### CODE REVIEW

File: tokio/tests/time_pause.rs [hunk 1]
```diff
@@ -215,6 +215,40 @@ async fn interval() {
...
+
+    assert_eq!(now.elapsed(), dur);
+
+    let now = Instant::now();
+    let dur = Duration::from_micros(3_123_456);
+    time::advance(dur).await;
+
+    assert_eq!(now.elapsed(), dur);
+}
+
```
Comment (sb64) [inline tokio/tests/time_pause.rs:251]:
```suggestion

#[tokio::test(start_paused = true)]
async fn regression_3710_with_submillis_advance() {
    let start = Instant::now();

    time::advance(Duration::from_millis(1)).await;

    let mut sleep = task::spawn(time::sleep_until(start + Duration::from_secs(60)));

    assert_pending!(sleep.poll());

    let before = Instant::now();
    let dur = Duration::from_micros(51_592);
    time::advance(dur).await;
    assert_eq!(before.elapsed(), dur);

    assert_pending!(sleep.poll());
}

#[tokio::test(start_paused = true)]
async fn exact_1ms_advance() {
    let now = Instant::now();

    let dur = Duration::from_millis(1);
    time::advance(dur).await;

    assert_eq!(now.elapsed(), dur);

    let now = Instant::now();
    let dur = Duration::from_millis(1);
    time::advance(dur).await;

    assert_eq!(now.elapsed(), dur);
}

```
I was worried that one of these tests might fail, but they both passed for me, so I guess everything's good to go! You're welcome to discard these, but if you do want to include these so that these potential issues don't regress in the future, you're welcome to.

File: tokio/tests/time_pause.rs [hunk 2]
```diff
@@ -215,6 +215,40 @@ async fn interval() {
     assert_pending!(poll_next(&mut i));
 }
 
+#[tokio::test]
+async fn test_time_advance_sub_ms() {
+    time::pause();
```
Comment (sb64) [inline tokio/tests/time_pause.rs:220]:
```suggestion
#[tokio::test(start_paused = true)]
async fn test_time_advance_sub_ms() {
```
Small cleanliness nit

File: tokio/tests/time_pause.rs [hunk 3]
```diff
@@ -215,6 +215,40 @@ async fn interval() {
...
+    let now = Instant::now();
+    let dur = Duration::from_micros(1);
+    time::advance(dur).await;
+
+    assert_eq!(now.elapsed(), dur);
+}
+
+#[tokio::test]
+async fn test_time_advance_3ms_and_change() {
+    time::pause();
```
Comment (sb64) [inline tokio/tests/time_pause.rs:237]:
```suggestion
#[tokio::test(start_paused = true)]
async fn test_time_advance_3ms_and_change() {
```
Small cleanliness nit

File: tokio/src/time/clock.rs [hunk 4]
```diff
@@ -124,7 +124,17 @@ cfg_test_util! {
...
+        //
+        // "sleep_until" is needed to ensure registered timers are fired after the
+        // advance call, however, it will also round up time to the nearest ms. To
+        // avoid this loss of precision, we sleep until the previous millisecond.
+        // If the advance is less than 1ms, then we just need to yield.
+        if duration >= Duration::from_millis(1) {
+            crate::time::sleep_until(until - Duration::from_millis(1)).await;
+        } else {
+            crate::task::yield_now().await;
+        }
```
Comment (Darksonn) [inline tokio/src/time/clock.rs:137]: Can we have a test that does the following:

 * Creates a timer with a duration of 1 ms.
 * Advances time by 0.25 ms.
 * Advances time by 1.50 ms.

and one that does this:

 * Creates a timer with a duration of 1 ms.
 * Advances time by 0.25 ms.
 * Advances time by 0.25 ms.
 * Advances time by 0.25 ms.
 * Advances time by 0.25 ms.

**Comment by Darksonn** [comment]
Does this PR affect #3763?

**Comment by carllerche** [comment]
> Does this PR affect #3763?

It should not.

**Comment by carllerche** [comment]
I rebased on 1.6.x so that this can go out as a patch, once it is ready.

File: tokio/src/time/clock.rs (hunk 4 above)
Comment (carllerche) [reply tokio/src/time/clock.rs:137]: Thanks, this uncovered a different bug.

**Comment by carllerche** [comment]
Pushed a change. Instead of using a sleep in `time::advance`, this fixes the root of the issue. When futures passed to `Runtime::block_on` are woken, it bypassed all the machinery around advancing time. By intercepting wakes in the time driver, we know when the block_on task is woken and skip advancing time in that case.

File: tokio/src/time/clock.rs (hunk 4 above)
Comment (carllerche) [reply tokio/src/time/clock.rs]: I added the tests.

File: tokio/src/time/driver/mod.rs [hunk 5]
```diff
@@ -91,6 +91,13 @@ pub(crate) struct Driver<P: Park + 'static> {
 
     /// Parker to delegate to
     park: P,
+
+    // When test-util is enabled, this tracks if the driver was woken before
+    // entering park. While it may look racy, it only has any effect when the
+    // clock is paused and pausing the clock is restricted to a single-threaded
+    // runtime.
+    #[cfg(feature = "test-util")]
+    did_wake: Arc<AtomicBool>,
```
Comment (Darksonn) [inline tokio/src/time/driver/mod.rs:100]: I don't really understand the comment on this. When is the time driver woken?

File: tokio/src/time/driver/mod.rs [hunk 6]
```diff
@@ -248,6 +266,18 @@ where
...
+        fn did_wake(&self) -> bool {
+            self.did_wake.swap(false, Ordering::SeqCst)
+        }
+    }
+
+    cfg_not_test_util! {
+        fn did_wake(&self) -> bool {
+            unreachable!()
+        }
+    }
```
Comment (Darksonn) [inline tokio/src/time/driver/mod.rs:280]: It would be neat if we didn't need this.

Comment (carllerche) [reply tokio/src/time/driver/mod.rs:280]: It's this way to avoid cfgs in the main code, which, IMO, is more confusing.

File: tokio/src/time/driver/mod.rs (hunk 5 above)
Comment (carllerche) [reply tokio/src/time/driver/mod.rs:100]: Any time Unpark::unpark() is called.

Comment (Darksonn) [reply tokio/src/time/driver/mod.rs:100]: So is that when a timer elapses?

Comment (carllerche) [reply tokio/src/time/driver/mod.rs:100]: Not exactly. When a timer elapses, the associated Waker is notified.

Wakers for the tokio runtime are implemented by scheduling the associated task then calling `unpark()` on the runtime. Calling unpark will interrupt an epoll_wait call within the runtime (wakeup the io::driver).

In the time driver, I am intercepting this call as a signal to tell the driver that "something" woke up the runtime, i.e. the timeout passed to `park()` did not elapse.

Futures passed to `Runtime::block_on` are not scheduled on the runtime the same way spawned futures are. When the basic_scheduler polls all scheduled tasks, it calls park(None), the timer driver changes None -> the duration until the next timeout elapses. If the task passed to `block_on` is awaiting on `task::yield_now()`, it will first have called `cx.waker().wake_by_ref()` which, in turn, will call `unpark()`. This is how the basic_scheduler avoids blocking forever when it calls `park(None)`.

File: tokio/src/time/driver/mod.rs (hunk 6 above)
Comment (carllerche) [reply tokio/src/time/driver/mod.rs:280]: Do you have thoughts on how it can be improved?

File: tokio/src/time/driver/mod.rs (hunk 5 above)
Comment (Darksonn) [reply tokio/src/time/driver/mod.rs:100]: That makes sense. In particular, the important piece is that `did_wake` tracks whether the timeout elapsed, or something else happened.

Can you add this to the comment in the PR?

File: tokio/src/time/driver/mod.rs (hunk 6 above)
Comment (Darksonn) [reply tokio/src/time/driver/mod.rs:280]: If you factor out this snippet to a function, then you can define _that_ function twice with and without `test-util`. Then the version without `test-util` can just call `park_timeout` directly.
```Rust
if clock.is_paused() {
    self.park.park_timeout(Duration::from_secs(0))?;

    // Simulate advancing time
    clock.advance(duration);
    // If the time driver was woken, then the park completed
    // before the "duration" elapsed (usually caused by a
    // yield in `Runtime::block_on`). In this case, we don't
    // advance the clock.
    if !self.did_wake() {
        // Simulate advancing time
        clock.advance(duration);
    }
} else {
    self.park.park_timeout(duration)?;
}
```

File: tokio/src/time/driver/mod.rs [hunk 7]
```diff
@@ -426,6 +456,33 @@ where
...
+}
+
+impl<P: Park + 'static> Unpark for TimerUnpark<P> {
+    fn unpark(&self) {
+        self.inner.unpark();
+
+        #[cfg(feature = "test-util")]
+        self.did_wake.store(true, Ordering::SeqCst);
+    }
+}
```
Comment (Darksonn) [inline tokio/src/time/driver/mod.rs:484]: I understand that we are dealing with a single-threaded runtime, but it seems like it would be more obviously correct if you swap the two lines in this function.

Comment (carllerche) [reply tokio/src/time/driver/mod.rs:484]: Probably a good idea.

**Comment by carllerche** [comment]
Applied feedback.

**Review by Darksonn — APPROVED** [review]
Looks good to me!
