### PR TITLE
Fix #5808: Handle possible dangling reference safely

### LINKED ISSUE #5080: LengthDelimitedCodec::length_field_type()/length_field_len() should also update max_frame_length
**Version** tokio-util v0.7.2

**Platform** Win7

**Description**
Currently `LengthDelimitedCodec`s `Encoder`truncates frame length, which leads to corrupted data (e.g. 6Mb frame prefixed with 2-bytes length).

I expected to see this happen:
- calling `length_field_type::<u16>()` (or `length_field_len(2)`) should also set `max_frame_length` to `min(65535, max_frame_length)`
- calling `max_frame_length(N)` should also update `length_field_len` to smallest M such that `N < (1 << 8*M)` (probably not a good idea since it will change network-lvl presentation... maybe panic, if `length_field_len` is too small to accomodate `N`?)

### LINKED ISSUE #5808: WaitForCancellationFutureOwned should use MaybeUninit
In tokio-util, we have a custom implementation of a self-referential struct called `WaitForCancellationFutureOwned`. To protect against issues with stack protectors, this type should be changed to wrap the `Notified` struct in a `MaybeUninit`. See [this thread][1] for more information.

I'm not sure whether we can keep using pin-project-lite with this fix. It is preferable to keep using pin-project-lite, but it is acceptable if we have to manually implement the pin projections instead.

Note that the reference inside `Notified` falls under the `&UnsafeCell<T>` exception, so the current implementation is not actually unsound. However, this relies on implementation details of Tokio, which we should avoid doing.

[1]: https://users.rust-lang.org/t/unsafe-code-review-semi-owning-weak-rwlock-t-guard/95706

### PR DESCRIPTION
**Pull request by matheus-consoli**
Attempts to fix #5808.

## Motivation

Handle `Notify` as a possible dangling reference to avoid Undefined Behavior.

Technically, this is not UB today because `Notify` uses an `UnsafeCell` internally, which prevents the problem with the pointer aliasing rules based on https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html.

## Solution

Wrap the reference holder with a `MaybeUninit`.

### CODE REVIEW

File: tokio-util/src/sync/cancellation_token.rs [hunk 1]
```diff
@@ -77,15 +77,62 @@ pin_project! {
...
+        // but camouflages the relationship with `'static`.
+        // This can lead to Undefined Behavior, breaking the pointer aliasing rules
+        // if the reference is dangling.
+        // This is fixed here by the use of `MaybeDanglingFuture`, which prevent
+        // the compiler to generate the UB.
         // Since `future` is the first field, it is dropped before the
         // cancellation_token field. This ensures that the reference inside the
-        // `Notified` remains valid.
+        // `Notified` remains valid, hance the safety requirements of
+        // `MaybeDanglingFuture` are satisfied.
```
Comment (Darksonn) [inline tokio-util/src/sync/cancellation_token.rs:89]: Hmm, I think this could be better phrased like this:
```text
This field internally has a reference to the cancellation token, but camouflages
the relationship with `'static`. To avoid undefined behavior, we must ensure
that the reference is only used while the cancellation token is still alive. To
do that, we ensure that the future is the first field, so that it is dropped
before the cancellation token.

We use `MaybeDanglingFuture` here because without it, the compiler could assert
the reference inside `future` to be valid even after the destructor of that
field runs. (Specifically, when the `WaitForCancellationFutureOwned` is passed
as an argument to a function, the reference can be asserted to be valid for the
rest of that function.) To avoid that, we use `MaybeDangling` which tells the
compiler that the reference stored inside it might not be valid.

See <https://users.rust-lang.org/t/unsafe-code-review-semi-owning-weak-rwlock-t-guard/95706>
for more info.
```

File: tokio-util/src/sync/cancellation_token.rs [hunk 2]
```diff
@@ -77,15 +77,62 @@ pin_project! {
...
+///
+/// The inner type must be dropped before the data it references to.
+///
+// Reference
+// See <https://users.rust-lang.org/t/unsafe-code-review-semi-owning-weak-rwlock-t-guard/95706>
+//
+// TODO: replace this with an official solution once RFC #3336 or similar is available.
+// <https://github.com/rust-lang/rfcs/pull/3336>
+#[repr(transparent)]
+struct MaybeDanglingFuture<T>(core::mem::MaybeUninit<T>);
```
Comment (Darksonn) [inline tokio-util/src/sync/cancellation_token.rs:109]: I would move this into another file.

**Review by Darksonn — COMMENTED** [review]
Thank you for the PR.

File: tokio-util/src/sync/cancellation_token.rs (hunk 1 above)
Comment (matheus-consoli) [reply tokio-util/src/sync/cancellation_token.rs]: Thanks, I think this is much clear indeed. I applied the suggestion.

File: tokio-util/src/sync/cancellation_token.rs (hunk 2 above)
Comment (matheus-consoli) [reply tokio-util/src/sync/cancellation_token.rs]: `MaybeDangling` was renamed and moved to a new file under `cancellation_token/` - I'm not sure if this is the best place, let me know if you think there's a better one :)

Comment (Darksonn) [reply tokio-util/src/sync/cancellation_token.rs]: One convention we use in the main Tokio crate is to have a `src/util` folder for this kind of thing. I guess the same could make sense here. (We already have a `mod util {}` in `lib.rs`, so it would have two things if we moved it there.)

Comment (matheus-consoli) [reply tokio-util/src/sync/cancellation_token.rs]: is it ok for you if I add it to the mod here and open another PR to extract the mod to a folder?

Comment (Darksonn) [reply tokio-util/src/sync/cancellation_token.rs]: Either is fine.

File: tokio-util/src/sync/cancellation_token/maybe_dangling.rs [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+//
+// TODO: replace this with an official solution once RFC #3336 or similar is available.
+// <https://github.com/rust-lang/rfcs/pull/3336>
+#[repr(transparent)]
+pub(crate) struct MaybeDangling<T>(MaybeUninit<T>);
+
+impl<T> Drop for MaybeDangling<T> {
+    fn drop(&mut self) {
+        // Safety: `0` is always initialized.
+        // It may be dangling, but it's the caller responsibility to ensure the data is valid.
```
Comment (Darksonn) [inline tokio-util/src/sync/cancellation_token/maybe_dangling.rs:25]: Actually, it should not be dangling at this point.
```suggestion
        // Safety: `0` is always initialized.
```

File: tokio-util/src/sync/cancellation_token/maybe_dangling.rs [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+        Self(MaybeUninit::new(inner))
+    }
+}
+
+impl<F: Future> Future for MaybeDangling<F> {
+    type Output = F::Output;
+
+    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
+        // Safety: `0` is always initialized.
+        // It may be dangling, but it's the caller responsibility to ensure the data is valid.
```
Comment (Darksonn) [inline tokio-util/src/sync/cancellation_token/maybe_dangling.rs:41]: Same here.
```suggestion
        // Safety: `0` is always initialized.
```

File: tokio-util/src/sync/cancellation_token/maybe_dangling.rs [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+use core::ptr;
+use core::task::{Context, Poll};
+
+/// A wrapper type that avoids implicitly asserting the contents are currently valid.
+/// It's safe to contain a dangling reference, as long as it is not used.
+///
+/// # Safety
+///
+/// The inner type must be dropped before the data it references to.
+///
```
Comment (Darksonn) [inline tokio-util/src/sync/cancellation_token/maybe_dangling.rs:13]: It doesn't really make much sense for this to have a safety comment. There are no safety requirements for the user; in fact, using this type gives the user _more_ abilities than they usually have. Safety comments always talk about reductions in what the user can do.
```suggestion
/// A wrapper type that tells the compiler that the contents might not be valid.
///
/// This is necessary mainly when `T` contains a reference. In that case, the
/// compiler will sometimes assume that the reference is always valid; in some
/// cases it will assume this even after the destructor of `T` runs. For
/// example, when a reference is used as a function argument, then the compiler
/// will assume that the reference is valid until the function returns, even if
/// the reference is destroyed during the function. When the reference is used
/// as part of a self-referential struct, that assumption can be false. Wrapping
/// the reference in this type prevents the compiler from making that
/// assumption.
///
/// # Invariants
///
/// The `MaybeUninit` will always contain a valid value until the destructor runs.
```

File: tokio-util/src/sync/cancellation_token/maybe_dangling.rs [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+// TODO: replace this with an official solution once RFC #3336 or similar is available.
+// <https://github.com/rust-lang/rfcs/pull/3336>
+#[repr(transparent)]
+pub(crate) struct MaybeDangling<T>(MaybeUninit<T>);
+
+impl<T> Drop for MaybeDangling<T> {
+    fn drop(&mut self) {
+        // Safety: `0` is always initialized.
+        // It may be dangling, but it's the caller responsibility to ensure the data is valid.
+        unsafe { ptr::drop_in_place(self.0.as_mut_ptr()) };
```
Comment (Darksonn) [inline tokio-util/src/sync/cancellation_token/maybe_dangling.rs:26]: Please add a test that ensures that the destructor actually runs.
```rust
#[test]
fn runs_drop() {
    struct SetOnDrop<'a>(&'a mut bool);

    impl Drop for SetOnDrop<'_> {
        fn drop(&mut self) {
            *self.0 = true;
        }
    }

    let mut success = false;

    drop(MaybeDangling::new(SetOnDrop(&mut success)));

    assert!(success);
}
```

File: tokio-util/src/sync/cancellation_token.rs (hunk 2 above)
Comment (matheus-consoli) [reply tokio-util/src/sync/cancellation_token.rs]: I decided to go with the `util` folder because it fits best with the organization/test

File: tokio-util/src/sync/cancellation_token/maybe_dangling.rs (hunk 5 above)
Comment (matheus-consoli) [reply tokio-util/src/sync/cancellation_token/maybe_dangling.rs]: Oh, totally makes sense

**Review by Darksonn — APPROVED** [review]
Thanks. Looks good to me.
