### PR TITLE
Fix for flaky worker_steal_count test

### LINKED ISSUE #6470: Test worker_steal_count hangs sometimes
I tried fixing this in the past with #6327, but it seems like that attempt was not enough to fix it, because it's still happening.

https://github.com/tokio-rs/tokio/blob/431b7c52636850820dd1f2b45e02c06cf366cb1c/tokio/tests/rt_metrics.rs#L177-L213

For now, I've ignored the test in #6471, but it should be fixed.

### PR DESCRIPTION
**Pull request by jofas**
Fixes #6470. Same approach as in #6916 for a similar flaky test that also relies on blocking the runtime. I tried corroborating the validity of this fix by running this test ~250k times successfully on my local machine, but I was unable to hit even a single retry in those runs.

### CODE REVIEW

File: tokio/tests/rt_unstable_metrics.rs [hunk 1]
```diff
@@ -295,37 +295,34 @@ fn worker_noop_count() {
...
 
     drop(rt);
 
+    if !successfully_spawned_stealable_task {
+        panic!("exhausted every try to schedule the stealable task");
+    }
+
     let n: u64 = (0..metrics.num_workers())
         .map(|i| metrics.worker_steal_count(i))
         .sum();
```
Comment (Darksonn) [inline tokio/tests/rt_unstable_metrics.rs:328]: We should recreate the runtime on failure. Otherwise a failed round could result in this number being wrong.

Comment (mox692) [reply tokio/tests/rt_unstable_metrics.rs:328]: Ah, I guess this clould be the case for #6916 too.

Comment (jofas) [reply tokio/tests/rt_unstable_metrics.rs:328]: > Ah, I guess this clould be the case for https://github.com/tokio-rs/tokio/pull/6916 too.

I don't _think_ the `global_queue_depth` in #6916 could be tainted by a task from the previous try to block the runtime. That would require both tasks from the next try to be scheduled before the one unscheduled (but already queued) task of the previous try, which I don't believe can happen? If that could happen, the test would be racy. I'm not exactly sure what guarantees Tokio has for task execution order. Even if my assumption is true, if we are relying on an implementation detail I think we should recreate the runtime in that test, too, to bullet proof it against future changes.

Comment (mox692) [reply tokio/tests/rt_unstable_metrics.rs:328]: If the deadlock scenario is what I mentioned [here](https://github.com/tokio-rs/tokio/pull/6876#issuecomment-2408993124), then one injection queue task will remain in the queue. So I think starting another iteration without refreshing the runtime could taint the queue.

Comment (jofas) [reply tokio/tests/rt_unstable_metrics.rs]: > So I think starting another iteration without refreshing the runtime could taint the queue.

That would require both tasks from the current try to block the runtime to be executed before the one remaining task from the previous try. Is that possible under the consideration that a task blocks the worker it is executed on? 

(Sorry for my ignorance of the implementation details, I've yet to fully grasp the execution model of the multi-threaded runtime)

Comment (Darksonn) [reply tokio/tests/rt_unstable_metrics.rs]: Yes, but it's probably pretty unlikely.

Comment (jofas) [reply tokio/tests/rt_unstable_metrics.rs]: Okay, then I should definitely revisit #6916 and recreate the runtime on each try. Should I make a new PR or do the changes here?

Comment (Darksonn) [reply tokio/tests/rt_unstable_metrics.rs]: Up to you. I would probably make a new PR.

Comment (jofas) [reply tokio/tests/rt_unstable_metrics.rs]: #6936 for reference.
