### PR TITLE
time: prevent `time::advance` from going too far

### LINKED ISSUE #3710: `time::advance` advances timer wheel too far when called after `time::Sleep` is `poll`ed
**Version**
tokio v1.5.0
tokio-macros v1.1.0 (proc-macro)
tokio-stream v0.1.5
tokio-test v0.4.1
tokio-util v0.6.6
└── tokio v1.4.0
├── tokio v1.4.0
├── tokio-stream v0.1.5
└── tokio-test v0.4.1
    ├── tokio v1.4.0
    └── tokio-stream v0.1.5

**Platform**
Linux laptop 5.11.14-arch1-1

**Description**
I've been working on a PR to implement #3574, but I'm struggling to prove my implementation works because of a bug in the Tokio clock. Specifically, when the time is paused and I called `poll` on a `Sleep` before calling `time::advance`, the runtime advances too far. For reference, `time::Interval` relies on `time::Sleep` under the hood, and it just `reset`s its internal `Sleep` to the next tick whenever it `tick`s. At the moment, `Interval`'s tests in `tokio/tests/time_interval.rs` pass, but that is a fluke. The first way I tried to debug this issue was to take a clean working tree of master and modify `time_interval.rs` by adding a line before and after each call to `time::advance` that checked that the runtime had advanced the correct amount. It was as follows:
```rust
let before = Instant::now();
time::advance(ms(100)).await;
assert_eq!(before.elapsed(), ms(100));
```
The entire test looked like this:
```rust
#[tokio::test]
async fn usage() {
    time::pause();

    let start = Instant::now();

    // TODO: Skip this
    time::advance(ms(1)).await;

    let mut i = task::spawn(time::interval_at(start, ms(300)));

    assert_ready_eq!(poll_next(&mut i), start);
    assert_pending!(poll_next(&mut i));

    let before = Instant::now();
    time::advance(ms(100)).await;
    assert_eq!(before.elapsed(), ms(100));
    assert_pending!(poll_next(&mut i));

    let before = Instant::now();
    time::advance(ms(200)).await;
    assert_eq!(before.elapsed(), ms(200));
    assert_ready_eq!(poll_next(&mut i), start + ms(300));
    assert_pending!(poll_next(&mut i));

    let before = Instant::now();
    time::advance(ms(400)).await;
    assert_eq!(before.elapsed(), ms(400));
    assert_ready_eq!(poll_next(&mut i), start + ms(600));
    assert_pending!(poll_next(&mut i));

    let before = Instant::now();
    time::advance(ms(500)).await;
    assert_eq!(before.elapsed(), ms(500));
    assert_ready_eq!(poll_next(&mut i), start + ms(900));
    assert_ready_eq!(poll_next(&mut i), start + ms(1200));
    assert_pending!(poll_next(&mut i));
}
```
This test failed with:
```
thread 'usage' panicked at 'assertion failed: `(left == right)`
  left: `255ms`,
 right: `100ms`', tokio/tests/time_interval.rs:32:5
```
The first call to `advance` after spawning the `Interval` failed (when I refer to a call to `advance` succeeding or failing, I refer to whether or not the runtime advanced the correct amount). I did some further testing with this test as a starting point, and I found that only the first call to `advance`, where it advances 100ms, ever failed. All subsequent `advance`s succeeded. I wondered if there was something special about the duration 100ms, so I changed that duration, and in every case, the runtime would advance 255ms, rather than the specified amount. However, once I called advance with a duration of 255ms or more, the call succeeded, as did all future calls to `advance`. In fact, the entire test succeeded for any call to `advance` with any `Duration` within the range of 255ms <= duration < 300ms. Once I `advance`d the runtime 300ms, the `Interval` would tick, which is why the test failed in that case. The test did not fail because the runtime advanced too far, however. At this point, I wondered if `advance` would fail with plain `Sleep`s. So I wrote up this test, which is very similar to how the test on `Interval` worked under the hood:
```rust
use tokio::time::{self, Duration, Instant};
use tokio_test::{assert_pending, task};

#[tokio::test]
async fn time_advance_bug() {
    time::pause();

    let start = Instant::now();

    // TODO: Skip this
    time::advance(ms(1)).await;

    let mut sleep = task::spawn(time::sleep_until(start + ms(300)));

    assert_pending!(sleep.poll());

    let before = Instant::now();
    time::advance(ms(100)).await;
    assert_eq!(before.elapsed(), ms(100));

    assert_pending!(sleep.poll());
}

fn ms(n: u64) -> Duration {
    Duration::from_millis(n)
}
```
It failed with a very similar message:
```
thread 'time_advance_bug' panicked at 'assertion failed: `(left == right)`
  left: `255ms`,
 right: `100ms`', tokio/tests/time_sleep_bug.rs:19:5
```
I wondered if `poll`ing the `Sleep` before `advance`ing the time was the issue, so I removed line 15, which was `assert_pending!(sleep.poll());` The test passed. It seemed that polling the `Sleep` before `advance`ing time was an issue. However, in my first round of tests, this wasn't an issue after the first call to `advance`, so I tried rewriting my test to run on one task (rather than spawning the `Sleep` on a separate task), to see if that was an issue (pardon the convoluted-ness):
```rust
use tokio::time::{self, Duration, Instant, Sleep};
use tokio_test::assert_pending;

use std::{
    future::Future,
    pin::Pin,
    task::{Context, Poll},
};

enum State {
    Begin,
    AwaitingAdvance(Pin<Box<dyn Future<Output = ()>>>),
    AfterAdvance,
}

struct Tester {
    sleep: Pin<Box<Sleep>>,
    state: State,
    before: Option<Instant>,
}

impl Future for Tester {
    type Output = ();

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        match &mut self.state {
            State::Begin => {
                assert_pending!(self.sleep.as_mut().poll(cx));
                self.before = Some(Instant::now());
                let advance_fut = Box::pin(time::advance(ms(100)));
                self.state = State::AwaitingAdvance(advance_fut);
                self.poll(cx)
            }
            State::AwaitingAdvance(ref mut advance_fut) => match advance_fut.as_mut().poll(cx) {
                Poll::Pending => Poll::Pending,
                Poll::Ready(()) => {
                    self.state = State::AfterAdvance;
                    self.poll(cx)
                }
            },
            State::AfterAdvance => {
                assert_eq!(self.before.unwrap().elapsed(), ms(100));

                assert_pending!(self.sleep.as_mut().poll(cx));

                Poll::Ready(())
            }
        }
    }
}

#[tokio::test]
async fn time_advance_bug() {
    time::pause();

    let start = Instant::now();

    // TODO: Skip this
    time::advance(ms(1)).await;

    let sleep = Box::pin(time::sleep_until(start + ms(300)));

    Tester {
        sleep,
        state: State::Begin,
        before: None,
    }
    .await;
}

fn ms(n: u64) -> Duration {
    Duration::from_millis(n)
}
```
It still failed:
```
thread 'time_advance_bug' panicked at 'assertion failed: `(left == right)`
  left: `255ms`,
 right: `100ms`', tokio/tests/failed_time_interval.rs:42:17
```
Once again, I tried not `poll`ing the `Sleep` before the call to `advance`, and the test passed. I therefore conclude that there must be some bug in the clock that causes it to advance too far when a `Sleep` is polled before a call to `advance`. I'm still not sure why none of the other polls on `Sleep` before `advance` in my first round of tests failed, because I wrote other tests that created a `Sleep`, `advance`d the time enough to resolve it, `reset` the `Sleep` to a new time in the future, `poll`ed it again, and then `advance`d the time, and those tests failed. This confuses me, because under the hood, that's what the tests on `Interval` were doing, and aside from the first call to `advance`. I wonder if the runtime only advances too far once, or something like that.

I'm also not sure about the significance of the duration 255ms. In every case where the runtime advanced too far, it advanced 255ms, rather than the amount it was supposed to. I will note that 255 is equivalent to `u8::MAX`, but I don't know if that matters, because I believe most things to do with time in Tokio are stored as `u64`s.

If someone could help me find the root cause of this issue and point me towards the file(s) to fix, I'd be happy to submit a PR for this. At this time, however, I don't know where to start looking to fix this bug, and the timer component intimidates me.

### PR DESCRIPTION
**Pull request by carllerche**
Previously, `time::advance` would set the mocked clock forward the
requested amount, then yield. However, if there was no work ready to
perform immediately, this would result in advancing to the next expiring
sleep.

Now, `time::advance(...)` will unblock at the requested time. The
difference between `time::advance(...)` and `time::sleep(...)` is a bit
fuzzy. The main difference is `time::sleep(...)` operates on the current
task and `time::advance(...)` operates at the runtime level.

Fixes #3710

### CODE REVIEW

File: tokio/tests/time_pause.rs [hunk 1]
```diff
@@ -57,3 +78,177 @@ async fn paused_time_stress_run() -> Vec<Duration> {
 
     times
 }
+
+#[tokio::test]
+async fn advance_after_poll() {
+    time::pause();
```
Comment (Darksonn) [inline tokio/tests/time_pause.rs:84]:
```suggestion
#[tokio::test(start_paused = true)]
async fn advance_after_poll() {
```

File: tokio/tests/time_pause.rs [hunk 2]
```diff
@@ -57,3 +78,177 @@ async fn paused_time_stress_run() -> Vec<Duration> {
...
+    assert_ready_eq!(poll_next(&mut i), start + ms(1200));
+    assert_pending!(poll_next(&mut i));
+}
+
+fn poll_next(interval: &mut task::Spawn<time::Interval>) -> Poll<Instant> {
+    interval.enter(|cx, mut interval| {
+        tokio::pin! {
+            let fut = interval.tick();
+        }
+        fut.poll(cx)
```
Comment (Darksonn) [inline tokio/tests/time_pause.rs:248]:
```suggestion
        interval.poll_tick(cx)
```

File: tokio/tests/time_pause.rs [hunk 3]
```diff
@@ -57,3 +78,170 @@ async fn paused_time_stress_run() -> Vec<Duration> {
...
+        state: State::Begin,
+        before: None,
+        poll: false,
+    }
+    .await;
+}
+
+#[tokio::test]
+async fn interval() {
+    time::pause();
```
Comment (Darksonn) [inline tokio/tests/time_pause.rs:204]:
```suggestion
#[tokio::test(start_paused = true)]
async fn interval() {
```

File: tokio/tests/time_pause.rs [hunk 4]
```diff
@@ -57,3 +78,170 @@ async fn paused_time_stress_run() -> Vec<Duration> {
...
+        state: State::Begin,
+        before: None,
+        poll: true,
+    }
+    .await;
+}
+
+#[tokio::test]
+async fn sleep_same_task_no_poll() {
+    time::pause();
```
Comment (Darksonn) [inline tokio/tests/time_pause.rs:184]:
```suggestion
#[tokio::test(start_paused = true)]
async fn sleep_same_task_no_poll() {
```

File: tokio/tests/time_pause.rs [hunk 5]
```diff
@@ -57,3 +78,170 @@ async fn paused_time_stress_run() -> Vec<Duration> {
...
+
+                Poll::Ready(())
+            }
+        }
+    }
+}
+
+#[tokio::test]
+async fn sleep_same_task() {
+    time::pause();
```
Comment (Darksonn) [inline tokio/tests/time_pause.rs:164]:
```suggestion
#[tokio::test(start_paused = true)]
async fn sleep_same_task() {
```

File: tokio/tests/time_pause.rs [hunk 6]
```diff
@@ -57,3 +78,170 @@ async fn paused_time_stress_run() -> Vec<Duration> {
...
+    let before = Instant::now();
+    time::advance(ms(100)).await;
+    assert_elapsed!(before, 100);
+
+    assert_pending!(sleep.poll());
+}
+
+#[tokio::test]
+async fn sleep_no_poll() {
+    time::pause();
```
Comment (Darksonn) [inline tokio/tests/time_pause.rs:101]:
```suggestion
#[tokio::test(start_paused = true)]
async fn sleep_no_poll() {
```

File: tokio/tests/time_pause.rs [hunk 7]
```diff
@@ -3,8 +3,29 @@
...
+
+        // Handles ms rounding
+        assert!(
+            elapsed >= lower && elapsed <= lower + ms(1),
+            "actual = {:?}, expected = {:?}",
+            elapsed,
+            lower
+        );
+    }};
+}
```
Comment (rcoh) [inline tokio/tests/time_pause.rs:28]: this would actually be an awesome macro to expose publicly, I end up adding a utility like this in any test cases I write that track time

Comment (Darksonn) [reply tokio/tests/time_pause.rs:28]: We already have similar macros in `tokio-test`. I don't see why we couldn't have this one there too

**Review by Darksonn — APPROVED** [review]
