### PR TITLE
sync: fix mpsc Disconnection docs to clarify recv returns None only when channel is empty

### LINKED ISSUE #6053: docs: `tokio::sync::mpsc` can still be read when all senders are dropped
Current phrasing in [tutorial](https://tokio.rs/tokio/tutorial/channels):

> When every Sender has gone out of scope or has otherwise been dropped, it is no longer possible to send more messages into the channel. At this point, the recv call on the Receiver will return None, which means that all senders are gone and the channel is closed.

The second statement is blatantly wrong because `recv` can still receive messages sent before senders drop.

```rust
use std::time::Duration;
use tokio::sync::mpsc;
use tokio::time::sleep;

#[tokio::main]
async fn main() {
    let (tx, mut rx) = mpsc::channel(32);
    let tx2 = tx.clone();

    tokio::spawn(async move {
        tx.send("sending from first handle").await.unwrap();
        drop(tx);
        println!("tx droppped");
    });

    tokio::spawn(async move {
        tx2.send("sending from second handle").await.unwrap();
        drop(tx2);
        println!("tx2 droppped");
    });

    sleep(Duration::from_secs(2)).await;

    while let Some(message) = rx.recv().await {
        println!("GOT = {}", message);
    }
}
```

In [docs](https://docs.rs/tokio/latest/tokio/sync/mpsc/index.html#disconnection):

> When all [Sender](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html) handles have been dropped, it is no longer possible to send values into the channel. This is considered the termination event of the stream. As such, Receiver::poll returns Ok(Ready(None)).

This looks more correct but I have never tested with `Receiver::poll`.

### PR DESCRIPTION
**Pull request by cluster2600**
Fixes #6053

## Problem

The `# Disconnection` section of the mpsc module docs stated:

> As such, `Receiver::poll` returns `Ok(Ready(None))`.

This is incorrect in two ways:

1. **Wrong condition**: When all `Sender` handles are dropped, `recv` does NOT immediately return `None`. Messages already buffered in the channel can still be received. `recv` only returns `None` once all senders are dropped **and** the channel has been fully drained.

2. **Wrong method name**: `Receiver::poll` is not a public API method. The public methods are `Receiver::recv` and `Receiver::poll_recv`.

## Fix

Update the documentation to accurately state that `recv` returns `None` (and `poll_recv` returns `Poll::Ready(None)`) only once all senders have been dropped **and** all buffered values have been received.

### CODE REVIEW

File: tokio/src/sync/mpsc/mod.rs [hunk 1]
```diff
@@ -29,7 +29,9 @@
 //!
 //! When all [`Sender`] handles have been dropped, it is no longer
 //! possible to send values into the channel. This is considered the termination
-//! event of the stream. As such, `Receiver::poll` returns `Ok(Ready(None))`.
+//! event of the stream. Once all senders have been dropped and any remaining
+//! buffered values have been received, `Receiver::recv` returns `None`
+//! (and `Receiver::poll_recv` returns `Poll::Ready(None)`).
```
Comment (Darksonn) [inline tokio/src/sync/mpsc/mod.rs:34]: This paragraph starts with "When all `Sender` handles have been dropped", so this seems a bit redundant to me.

**Comment by cluster2600** [comment]
The test failure `test_nested_block_in_place_with_block_on_between` seems to be a panic in `num_idle_threads` underflow. This looks unrelated to this docs-only change (which only touches `tokio/src/sync/mpsc/mod.rs`). Is this a known flaky test or an issue with the CI environment?

**Comment by Darksonn** [comment]
Yes it was introduced recently and we're working on fixing the flaky test.
