### PR TITLE
rt: add a method to retrieve task id

### LINKED ISSUE #1996: async fn and async block  not support  task::current().id(),how to get Coroutines id?
``` rust
#[tokio::main]
async fn main() {
   // application comes here
   println!("id = {:?}", task::current().id());
}
```
```
thread 'main' panicked at '`task::current()` called outside the context of a task', src/libcore/option.rs:1190:5
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: std::panicking::try::do_call
   8: std::panicking::begin_panic
   9: std::panicking::begin_panic
  10: core::option::Option<T>::expect
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/option.rs:345
  11: async_std::task::current::current
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.2.0/src/task/current.rs:26
  12: rbatis::main::{{closure}}
             at src/main.rs:68
  13: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:43
  14: std::future::set_task_context
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:79
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:43
  16: tokio::runtime::enter::Enter::block_on
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/enter.rs:100
  17: tokio::runtime::thread_pool::ThreadPool::block_on::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/thread_pool/mod.rs:102
  18: tokio::runtime::global::with_state::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:100
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  20: std::thread::local::LocalKey<T>::with
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  21: tokio::runtime::global::with_state
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:83
  22: tokio::runtime::global::with_thread_pool
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:75
  23: tokio::runtime::thread_pool::spawner::Spawner::enter
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/thread_pool/spawner.rs:44
  24: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/thread_pool/mod.rs:100
  25: tokio::runtime::Runtime::block_on::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/mod.rs:421
  26: tokio::runtime::global::with_state::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:100
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  28: std::thread::local::LocalKey<T>::with
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  29: tokio::runtime::global::with_state
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:83
  30: tokio::runtime::global::with_thread_pool
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:75
  31: tokio::runtime::thread_pool::spawner::Spawner::enter
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/thread_pool/spawner.rs:44
  32: tokio::runtime::spawner::Spawner::enter
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/spawner.rs:32
  33: tokio::runtime::handle::Handle::enter::{{closure}}::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/handle.rs:36
  34: tokio::time::clock::Clock::enter
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/time/clock.rs:30
  35: tokio::runtime::time::variant::with_default
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/time.rs:43
  36: tokio::runtime::handle::Handle::enter::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/handle.rs:36
  37: tokio::runtime::blocking::pool::Spawner::enter::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/blocking/pool.rs:191
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  39: std::thread::local::LocalKey<T>::with
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  40: tokio::runtime::blocking::pool::Spawner::enter
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/blocking/pool.rs:176
  41: tokio::runtime::handle::Handle::enter
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/handle.rs:33
  42: tokio::runtime::Runtime::block_on
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/mod.rs:416
  43: rbatis::main
             at src/main.rs:65
  44: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  45: std::panicking::try::do_call
  46: panic_unwind::dwarf::eh::read_encoded_pointer
  47: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
  48: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  49: rbatis::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by agayev**
Fixes #1996.
Closes #4721.

### CODE REVIEW

**Comment by agayev** [comment]
After the first PR, I realized that I haven't put added the test that forces a panic, and after I added that test, it failed; trying to figure out why....

File: tokio/src/runtime/task/mod.rs [hunk 1]
```diff
@@ -201,10 +201,21 @@ use std::{fmt, mem};
...
+#[derive(Copy, Clone, Debug, Hash, Eq, PartialEq)]
 pub struct Id(u64);
 
+/// Returns the `Id` of the task.
+///
+/// # Panics
+///
+/// This function panics if called from outside a task.
+///
+#[allow(unreachable_pub)]
```
Comment (Darksonn) [inline tokio/src/runtime/task/mod.rs:213]:
```suggestion
#[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
```

File: tokio/src/runtime/task/mod.rs [hunk 2]
```diff
@@ -201,10 +201,21 @@ use std::{fmt, mem};
...
+pub fn id() -> Id {
```
Comment (Darksonn) [inline tokio/src/runtime/task/mod.rs:214]: I would prefer to use a different name here. Probably something that contains "current".

File: tokio/src/runtime/task/mod.rs [hunk 3]
```diff
@@ -201,10 +201,21 @@ use std::{fmt, mem};
...
-#[derive(Clone, Debug, Hash, Eq, PartialEq)]
+#[derive(Copy, Clone, Debug, Hash, Eq, PartialEq)]
 pub struct Id(u64);
 
+/// Returns the `Id` of the task.
+///
+/// # Panics
+///
+/// This function panics if called from outside a task.
+///
```
Comment (Darksonn) [inline tokio/src/runtime/task/mod.rs:212]: This should mention that `block_on` calls currently don't have an id.

File: tokio/tests/task_panic.rs [hunk 4]
```diff
@@ -120,3 +120,16 @@ fn local_key_get_panic_caller() -> Result<(), Box<dyn Error>> {
...
+fn task_id_handle_panic_caller() -> Result<(), Box<dyn Error>> {
+    let panic_location_file = test_panic(|| {
+        let _ = task::id();
+    });
+
+    // The panic location should be in this file
+    assert_eq!(&panic_location_file.unwrap(), file!());
+
+    Ok(())
+}
```
Comment (Darksonn) [inline tokio/tests/task_panic.rs:135]: I don't think this test passes today. You need a `#[track_caller]` annotation.

File: tokio/tests/task_local.rs [hunk 5]
```diff
@@ -116,3 +116,64 @@ async fn task_local_available_on_completion_drop() {
     assert_eq!(rx.await.unwrap(), 42);
     h.await.unwrap();
 }
+
```
Comment (Darksonn) [inline tokio/tests/task_local.rs:119]: Please add the following tests:

 * Can get id from `spawn_blocking` task.
 * Can get id from `spawn_local` task on a `LocalSet`.
 * Can't get id in `block_on` call.
 * Can get id in future destructor when it completes normally.
 * Can get id in future destructor when it is aborted with `JoinHandle::abort`.
 * Can get id in destructor of output when `JoinHandle` dropped before task completion.
 * Can get id in destructor of output when `JoinHandle` dropped after task completion.
 * If you use a `LocalSet` to run a local task within another task, the original task's id is not erased once we return.
 * If you use `block_in_place` + `spawn` + `block_on` on a current-thread runtime to execute a spawned task within another task, the original task's id is not erased.

**Review by Darksonn — COMMENTED** [review]
In general, this change looks very good. It is rather compact, which is nice. I have a bunch of comments related to making sure that ids are set properly during destructors and that nested tasks handle ids correctly, and I expect some of the requested tests to fail under the current code. However, I believe that the changes to fix this are relatively small.

File: tokio/src/runtime/task/mod.rs (hunk 2 above)
Comment (agayev) [reply tokio/src/runtime/task/mod.rs:214]: Something with "current" makes sense in within the context of "Context", because different tasks come and go, but in the context of a "task", I don't think it makes sense -- a task has a single id during its lifetime, so I think task::id() is better.

File: tokio/src/runtime/context.rs [hunk 6]
```diff
@@ -85,6 +88,18 @@ cfg_rt! {
 
     pub(crate) struct DisallowBlockInPlaceGuard(bool);
 
+    pub(crate) fn set_current_task_id(id: Option<Id>) {
+        CONTEXT.with(|ctx| ctx.current_task_id.replace(id));
+    }
```
Comment (Darksonn) [inline tokio/src/runtime/context.rs:93]: This will panic if it runs during the destructor of a thread-local. I would silently do nothing here so that destructors can still run even if thread-locals are not available.

Some sort of test for this would be nice as well, but there are already existing bugs related to this (see #5162), and you don't have to fix those in this PR, so you should only add such a test if it doesn't hit an existing bug about this.

File: tokio/tests/task_local.rs (hunk 5 above)
Comment (agayev) [reply tokio/tests/task_local.rs:119]: > Please add the following tests:
> 
> * ~~Can get id from `spawn_blocking` task.~~
> * ~~Can get id from `spawn_local` task on a `LocalSet`.~~
> * ~~Can't get id in `block_on` call.~~
> * ~~Can get id in future destructor when it completes normally.~~
> * ~~Can get id in future destructor when it is aborted with `JoinHandle::abort`.~~
> * Can get id in destructor of output when `JoinHandle` dropped before task completion.
> * Can get id in destructor of output when `JoinHandle` dropped after task completion.
> * If you use a `LocalSet` to run a local task within another task, the original task's id is not erased once we return.
> * If you use `block_in_place` + `spawn` + `block_on` on a current-thread runtime to execute a spawned task within another task, the original task's id is not erased.

Comment (agayev) [reply tokio/tests/task_local.rs:119]: > Please add the following tests:
> 
> ~~* Can get id from `spawn_blocking` task.~~
> ~~* Can get id from `spawn_local` task on a `LocalSet`.~~
> ~~* Can't get id in `block_on` call.~~
> ~~* Can get id in future destructor when it completes normally.~~
> ~~* Can get id in future destructor when it is aborted with `JoinHandle::abort`.~~
> ~~* Can get id in destructor of output when `JoinHandle` dropped before task completion.~~
> * Can get id in destructor of output when `JoinHandle` dropped after task completion.
> ~~* If you use a `LocalSet` to run a local task within another task, the original task's id is not erased once we return.~~
> * If you use `block_in_place` + `spawn` + `block_on` on a current-thread runtime to execute a spawned task within another task, the original task's id is not erased.

@Darksonn I've added the tests that I've struck through. Can you please check if they make sense? I'm not confident about some of them. I'll add the remaining tests soon.

File: tokio/src/runtime/context.rs [hunk 7]
```diff
@@ -101,6 +104,18 @@ cfg_rt! {
...
 
+    pub(crate) fn set_current_task_id(id: Option<Id>) {
+        let _ = CONTEXT.try_with(|ctx| ctx.current_task_id.replace(id));
+    }
+
+    #[track_caller]
+    pub(crate) fn current_task_id() -> Id {
+        match CONTEXT.try_with(|ctx| ctx.current_task_id.get()) {
+            Ok(Some(id)) => id,
+            _ => panic!("can't get a task id when not inside a task"),
```
Comment (hawkw) [inline tokio/src/runtime/context.rs:115]: will this panic ever be encountered by a user, or does it indicate an internal bug? if it's going to be encountered if user code tries to get the current task ID outside of a task, it should probably explain a bit more about what happened. on the other hand, if it indicates a bug in Tokio, we should probably use `unreachable!` and state that this is a Tokio bug that should be reported.

Comment (Darksonn) [reply tokio/src/runtime/context.rs:115]: Yeah, you will hit this if you call `task::id()` from outside of a task.

File: tokio/src/runtime/task/mod.rs (hunk 2 above)
Comment (agayev) [reply tokio/src/runtime/task/mod.rs:218]: @hawkw thanks for the review!

I like ```task::id()``` better because it is what the name says. When I see that call, it is clear that the it returns the task's id. When I see ```Id::current()```, it is confusing because what would a non-current id be? If I call it again later, will the id be different? But I won't fight for it -- if you folks think ```Id::current()``` is better I can change it to that.

File: tokio/src/runtime/task/mod.rs [hunk 8]
```diff
@@ -201,10 +201,40 @@ use std::{fmt, mem};
...
 pub struct Id(u64);
 
+use crate::runtime::context;
+
+/// Returns the `Id` of the task.
+///
+/// # Panics
+///
+/// This function panics if called from outside a task or if called from a
+/// future passed to `block_on` call.
```
[the remark this answers is not in the document]
Comment (agayev) [reply tokio/src/runtime/task/mod.rs:214]: I'm okay changing it to return ```Option<Id>```.

File: tokio/src/runtime/task/mod.rs [hunk 9]
```diff
@@ -201,10 +201,40 @@ use std::{fmt, mem};
...
+pub fn id() -> Id {
+    use crate::runtime::context;
+    context::current_task_id()
+}
+
+/// Guard that sets and clears the task id in the context during task execution
+/// and cancellation.
+pub(crate) struct TaskIdGuard {}
+impl TaskIdGuard {
+    fn new(id: Id) -> Self {
```
[the remark this answers is not in the document]
Comment (agayev) [reply tokio/src/runtime/task/mod.rs:227]: Sounds good, will change it to ```enter```.

File: tokio/tests/task_local.rs [hunk 10]
```diff
@@ -117,3 +117,187 @@ async fn task_local_available_on_completion_drop() {
...
+}
+
+#[tokio::test(flavor = "current_thread")]
+async fn task_id_spawn_blocking() {
+    use tokio::task;
+
+    tokio::spawn(async { println!("task id: {}", task::id()) })
+        .await
+        .unwrap();
+}
```
[the remark this answers is not in the document]
Comment (agayev) [reply tokio/tests/task_local.rs:137]: Thanks for catching this. Will fix.

File: tokio/src/runtime/task/mod.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (hawkw) [reply tokio/src/runtime/task/mod.rs:214]: @Darksonn what do you think about the API surface for this?

[the remark this answers is not in the document]
Comment (Darksonn) [reply tokio/src/runtime/task/mod.rs:214]: I think having an `id()` and `try_id()` makes sense to me.

[the remark this answers is not in the document]
Comment (agayev) [reply tokio/src/runtime/task/mod.rs:214]: Ok.

**Comment by agayev** [comment]
@hawkw @Darksonn taking a step back and looking at it again, I think it will be cleaner if we store `task_id` in `Stage` enum, as in:

```
pub(super) enum Stage<T: Future> {
    Running(T, Id),
    Finished(super::Result<T::Output>, Id),
    Consumed,
}
```

I already suggested this to @Darksonn in discord and she dismissed it, but I didn't give my reasoning back then, so let me give it now.

Only three functions need to set the task id in the context:

* `CoreStage::poll` -- for making id available during the normal execution of the task
* `CoreStage::drop_future_or_output` -- for making id available when dropping a future or output
* `CoreStage::store_output` -- for making id available during the dropping of future

If we store id in the Stage enum, we can keep id setting stuff completely within core.rs file in just those functions and not leak it outside, and we can be sure that all future uses of these functions and moving them around will be covered. Otherwise, what we have currently is not reliable because we should find places where one of those functions are called and put TaskIdGuard around it.

The alternative is to change those three functions to accept the id argument and then have them enter the guards. I've partially done this for `store_output` in this PR, but it is incomplete/inconsistent at the moment: I set TaskGuardId in poll_future, which covers both, the call to `core.poll(cx)` and the call to `store_output`. So when the future destructor runs during the call to `store_output`, it can access the id. I've extended Stage enum to store Id with Finished variant, so `store_output` saves the Id there, so that when `drop_future_output` drops the output there, the output destructor can also access the id. As you can tell, this is messy and inconsistent.

Which one do you prefer, or do you have a better suggestion?

**Comment by Darksonn** [comment]
Thank you, that motivation seems reasonable enough. However, there's also another option: move the `CoreStage` methods to `Core` instead, so that they can access the id without changing the struct layout. What do you think?

**Comment by agayev** [comment]
> Thank you, that motivation seems reasonable enough. However, there's also another option: move the `CoreStage` methods to `Core` instead, so that they can access the id without changing the struct layout. What do you think?
> 
> I would prefer a solution where the id is not deleted from the task when the output is consumed so that the `id` field can be removed from `JoinHandle` in the future:
> 
> ```rust
> pub struct JoinHandle<T> {
>     raw: Option<RawTask>,
>     id: Id,
>     _p: PhantomData<T>,
> }
> ```

Sure, that also works. See https://github.com/tokio-rs/tokio/pull/5182.

File: tokio/src/runtime/context.rs [hunk 11]
```diff
@@ -107,6 +110,15 @@ cfg_rt! {
...
     pub(crate) struct DisallowBlockInPlaceGuard(bool);
 
+    pub(crate) fn set_current_task_id(id: Option<Id>) -> Option<Id> {
+        CONTEXT.try_with(|ctx| ctx.current_task_id.replace(id)).unwrap_or(None)
+    }
+
+    #[track_caller]
+    pub(crate) fn current_task_id() -> Option<Id> {
+        CONTEXT.try_with(|ctx| ctx.current_task_id.get()).unwrap_or(None)
+    }
```
Comment (Darksonn) [inline tokio/src/runtime/context.rs:120]: This can no longer panic, so you can remove the `#[track_caller]`.

File: tokio/src/runtime/task/core.rs [hunk 12]
```diff
@@ -202,6 +222,7 @@ impl<T: Future, S: Schedule> Core<T, S> {
     pub(super) fn drop_future_or_output(&self) {
         // Safety: the caller ensures mutual exclusion to the field.
         unsafe {
+            let _guard = TaskIdGuard::enter(self.task_id);
             self.set_stage(Stage::Consumed);
         }
```
Comment (Darksonn) [inline tokio/src/runtime/task/core.rs:227]: Maybe this should happen inside `set_stage`?  Currently you're missing it in `store_output`.

File: tokio/src/runtime/task/mod.rs [hunk 13]
```diff
@@ -201,10 +201,32 @@ use std::{fmt, mem};
 /// [unstable]: crate#unstable-features
 #[cfg_attr(docsrs, doc(cfg(all(feature = "rt", tokio_unstable))))]
 #[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
-// TODO(eliza): there's almost certainly no reason not to make this `Copy` as well...
-#[derive(Clone, Debug, Hash, Eq, PartialEq)]
+#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq)]
 pub struct Id(u64);
 
+/// Returns the `Id` of the task.
```
Comment (Darksonn) [inline tokio/src/runtime/task/mod.rs:207]:
```suggestion
/// Returns the id of the currently running task.
```

File: tokio/src/runtime/task/mod.rs [hunk 14]
```diff
@@ -201,10 +201,32 @@ use std::{fmt, mem};
...
+///
+/// # Panics
+///
+/// This function panics if called from outside a task or if called from a
+/// future passed to `block_on` call.
```
Comment (Darksonn) [inline tokio/src/runtime/task/mod.rs:212]: I would like more details. Something like "Please note that calls to `block_on` do not have task ids, so the method will panic if called from within a call to `block_on`."

File: tokio/src/runtime/task/mod.rs [hunk 15]
```diff
@@ -201,10 +201,32 @@ use std::{fmt, mem};
...
+}
+
+/// Returns the `Id` of the task if called from inside the task, or None otherwise.
+///
+#[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
+#[track_caller]
+pub fn try_id() -> Option<Id> {
+    use crate::runtime::context;
+    context::current_task_id()
+}
```
Comment (Darksonn) [inline tokio/src/runtime/task/mod.rs:228]: The documentation here is not sufficient. At least, it should link to the other function.

File: tokio/src/runtime/task/mod.rs [hunk 16]
```diff
@@ -201,10 +201,32 @@ use std::{fmt, mem};
 /// [unstable]: crate#unstable-features
 #[cfg_attr(docsrs, doc(cfg(all(feature = "rt", tokio_unstable))))]
 #[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
-// TODO(eliza): there's almost certainly no reason not to make this `Copy` as well...
-#[derive(Clone, Debug, Hash, Eq, PartialEq)]
+#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq)]
 pub struct Id(u64);
```
Comment (Darksonn) [inline tokio/src/runtime/task/mod.rs:205]: Please add documentation to this type that links to the `id` methods.

File: tokio/src/task/mod.rs [hunk 17]
```diff
@@ -319,6 +319,8 @@ cfg_rt! {
 
     cfg_unstable! {
         pub use crate::runtime::task::Id;
+        pub use crate::runtime::task::id;
+        pub use crate::runtime::task::try_id;
```
Comment (Darksonn) [inline tokio/src/task/mod.rs:323]:
```suggestion
        pub use crate::runtime::task::{Id, id, try_id};
```

**Review by Darksonn — COMMENTED** [review]
I haven't looked over the tests yet, but in general this looks quite nice and clean. :+1:

File: tokio/src/runtime/task/core.rs (hunk 12 above)
Comment (agayev) [reply tokio/src/runtime/task/core.rs:227]: I thought of it, but I think -- but not sure -- that a call to `store_output` is always preceded by a call to `drop_future_or_output`, which already destructs the future in the stage, so the guards are unnecessary. Anyway, moving it back to `set_stage`.

File: tokio/src/runtime/task/core.rs [hunk 18]
```diff
@@ -157,6 +158,24 @@ impl<T: Future> CoreStage<T> {
...
+    parent_task_id: Option<Id>,
+}
+impl TaskIdGuard {
+    fn enter(id: Id) -> Self {
+        TaskIdGuard {
+            parent_task_id: context::set_current_task_id(Some(id)),
+        }
+    }
+}
+impl Drop for TaskIdGuard {
```
Comment (hawkw) [inline tokio/src/runtime/task/core.rs:173]: very minor nit: in general, we add a line of whitespace between impl blocks:
```suggestion
}

impl TaskIdGuard {
    fn enter(id: Id) -> Self {
        TaskIdGuard {
            parent_task_id: context::set_current_task_id(Some(id)),
        }
    }
}

impl Drop for TaskIdGuard {
```

File: tokio/src/runtime/task/mod.rs [hunk 19]
```diff
@@ -193,6 +193,9 @@ use std::{fmt, mem};
 ///   task completes, the same ID may be used for another task.
 /// - Task IDs are *not* sequential, and do not indicate the order in which
 ///   tasks are spawned, what runtime a task is spawned on, or any other data.
+/// - Task ID of a task can be obtained via the functions
+///   [`task::try_id()`](crate::runtime::task::try_id()) and
+///   [`task::id()`](crate::runtime::task::id()).
```
Comment (hawkw) [inline tokio/src/runtime/task/mod.rs:198]: the way this is worded, it sounds kind of like these functions can be used to get the task ID of _any_ task...what if we re-worded this to:
```suggestion
/// - The task ID of the currently running task can be obtained via the
///   [`task::try_id()`](crate::runtime::task::try_id()) and
///   [`task::id()`](crate::runtime::task::id()) functions.
```

and it might also be worth mentioning that `JoinHandle::id` can also be used to access a task's ID through a `JoinHandle`...

File: tokio/src/runtime/task/mod.rs [hunk 20]
```diff
@@ -201,10 +204,36 @@ use std::{fmt, mem};
 /// [unstable]: crate#unstable-features
 #[cfg_attr(docsrs, doc(cfg(all(feature = "rt", tokio_unstable))))]
 #[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
-// TODO(eliza): there's almost certainly no reason not to make this `Copy` as well...
-#[derive(Clone, Debug, Hash, Eq, PartialEq)]
+#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq)]
 pub struct Id(u64);
 
+/// Returns the id of the currently running task.
```
Comment (hawkw) [inline tokio/src/runtime/task/mod.rs:210]: nit:
```suggestion
/// Returns the [`Id`] of the currently running task.
````

File: tokio/src/runtime/task/mod.rs [hunk 21]
```diff
@@ -201,10 +204,36 @@ use std::{fmt, mem};
...
+///
+/// # Panics
+///
+/// This function panics if called from outside a task. Please note that calls
+/// to `block_on` do not have task ids, so the method will panic if called from
```
Comment (hawkw) [inline tokio/src/runtime/task/mod.rs:215]:
```suggestion
/// to `block_on` do not have task IDs, so the method will panic if called from
```

File: tokio/src/runtime/task/mod.rs [hunk 22]
```diff
@@ -201,10 +204,36 @@ use std::{fmt, mem};
...
+#[track_caller]
+pub fn id() -> Id {
+    use crate::runtime::context;
+    context::current_task_id().expect("Can't get a task id when not inside a task")
+}
+
+/// Returns the id of the currently running task. This function is similar to
+/// [`task::id()`](crate::runtime::task::id()), except it doesn't panic and
+/// returns `None` if the id is unavailable.
+///
```
Comment (hawkw) [inline tokio/src/runtime/task/mod.rs:229]: nit: maybe:
```suggestion
/// Returns the [`Id`] of the currently running task, or `None` if called outside
/// of a task.
///
/// This function is similar to  [`task::id()`](crate::runtime::task::id()), except
/// that it returns `None` rather than panicking if called outside of a task 
/// context.
```

File: tokio/src/runtime/task/mod.rs [hunk 23]
```diff
@@ -201,10 +204,36 @@ use std::{fmt, mem};
...
+/// This function panics if called from outside a task. Please note that calls
+/// to `block_on` do not have task ids, so the method will panic if called from
+/// within a call to `block_on`. For a version of this function that doesn't
+/// panic, see [`task::try_id()`](crate::runtime::task::try_id()).
+///
+#[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
+#[track_caller]
+pub fn id() -> Id {
+    use crate::runtime::context;
```
Comment (hawkw) [inline tokio/src/runtime/task/mod.rs:222]: style nit, take it or leave it: since this is used in two functions in this module, i think it would be fine to import it at the top of the module?

File: tokio/src/runtime/task/mod.rs (hunk 19 above)
Comment (hawkw) [reply tokio/src/runtime/task/mod.rs:198]: also, do we know if these links actually work correctly in the RustDoc documentation? the `tokio::runtime::task` module is not public, and these functions are re-exported publicly from `tokio::task`, so should the link references instead refer to `crate::task::id()` etc?

File: tokio/src/runtime/task/mod.rs [hunk 24]
```diff
@@ -201,10 +204,36 @@ use std::{fmt, mem};
...
 
+/// Returns the id of the currently running task.
+///
+/// # Panics
+///
+/// This function panics if called from outside a task. Please note that calls
+/// to `block_on` do not have task ids, so the method will panic if called from
+/// within a call to `block_on`. For a version of this function that doesn't
+/// panic, see [`task::try_id()`](crate::runtime::task::try_id()).
+///
```
Comment (hawkw) [inline tokio/src/runtime/task/mod.rs:218]: in general, unstable APIs have a note in their documentation stating that they are unstable and referencing the section in the `lib.rs` docs that explain what it means for an API to be unstable. can we add that here?
```suggestion
/// **Note**: This is an [unstable API][unstable]. The public API of this type
/// may break in 1.x releases. See [the documentation on unstable
/// features][unstable] for details.
///
/// [task ID]: crate::task::Id
```

File: tokio/src/runtime/task/mod.rs [hunk 25]
```diff
@@ -201,10 +204,36 @@ use std::{fmt, mem};
...
+pub fn id() -> Id {
+    use crate::runtime::context;
+    context::current_task_id().expect("Can't get a task id when not inside a task")
+}
+
+/// Returns the id of the currently running task. This function is similar to
+/// [`task::id()`](crate::runtime::task::id()), except it doesn't panic and
+/// returns `None` if the id is unavailable.
+///
+#[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
```
Comment (hawkw) [inline tokio/src/runtime/task/mod.rs:230]: let's add the unstable API note at the end of the docs here:
```suggestion
///
/// **Note**: This is an [unstable API][unstable]. The public API of this type
/// may break in 1.x releases. See [the documentation on unstable
/// features][unstable] for details.
///
/// [task ID]: crate::task::Id
#[cfg_attr(not(tokio_unstable), allow(unreachable_pub))]
```

File: tokio/tests/task_local.rs [hunk 26]
```diff
@@ -117,3 +117,209 @@ async fn task_local_available_on_completion_drop() {
...
+#[test]
+fn task_try_id_inside_block_on() {
+    use tokio::runtime::Runtime;
+    use tokio::task;
+
+    let rt = Runtime::new().unwrap();
+    rt.block_on(async {
+        assert_eq!(None, task::try_id());
+    });
+}
```
Comment (hawkw) [inline tokio/tests/task_local.rs:325]: i'm not sure if the `task_local` file here is the correct place for the task ID tests --- this module has the tests for the `task_local!` macro, which isn't really related to the task ID APIs.

i think we should probably add a new `task_id.rs` file in `tokio/tests` for these tests, instead.

**Review by hawkw — COMMENTED** [review]
overall, the implementation looks good to me! most of my remaining suggestions concern the documentation and tests added in this PR.

**Comment by hawkw** [comment]
it looks like there are currently some test failures when building with `--no-default-features`: https://github.com/tokio-rs/tokio/actions/runs/3439239014/jobs/5736297357#step:9:14

File: tokio/src/runtime/task/mod.rs (hunk 19 above)
Comment (agayev) [reply tokio/src/runtime/task/mod.rs:198]: I've changed them to `crate::task::id`. Right now when I build docs, I get some unresolved link errors, so I can't test them right now, but I will test them once I get the doc building working.

File: tokio/tests/task_local.rs (hunk 5 above)
Comment (agayev) [reply tokio/tests/task_local.rs]: added the last test as well.

**Comment by agayev** [comment]
@Darksonn @hawkw passed all the tests -- ready for review!

File: tokio/tests/task_id.rs [hunk 27]
```diff
@@ -0,0 +1,298 @@
...
+    }
+
+    impl Drop for MyFuture {
+        fn drop(&mut self) {
+            println!("task id: {}", task::id());
+        }
+    }
+
+    tokio::spawn(MyFuture).await.unwrap();
+}
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:107]: I'm not sure that this test will fail even if a panic happens. You should send a notification back to the main function and assert the success there.

File: tokio/tests/task_id.rs [hunk 28]
```diff
@@ -0,0 +1,298 @@
...
+        }
+    }
+    impl Drop for MyFuture {
+        fn drop(&mut self) {
+            println!("task id: {}", task::id());
+        }
+    }
+
+    tokio::spawn(MyFuture).abort();
+}
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:128]: This one _definitely_ wont fail if the destructor panics.

File: tokio/tests/task_id.rs [hunk 29]
```diff
@@ -0,0 +1,298 @@
...
+fn task_id_outside_task_panic_caller() -> Result<(), Box<dyn Error>> {
+    let panic_location_file = test_panic(|| {
+        let _ = task::id();
+    });
+
+    // The panic location should be in this file
+    assert_eq!(&panic_location_file.unwrap(), file!());
+
+    Ok(())
+}
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:264]: The panic location tests should be last or in a separate file.

File: tokio/tests/task_id.rs [hunk 30]
```diff
@@ -0,0 +1,298 @@
...
+
+#[cfg(tokio_unstable)]
+#[tokio::test(flavor = "multi_thread")]
+async fn task_id_block_in_place_block_on_spawn() {
+    task::spawn(async {
+        let id1 = task::id();
+
+        task::block_in_place(|| {
+            let rt = Builder::new_current_thread().build().unwrap();
+            rt.block_on(rt.spawn(async {})).unwrap();
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:290]: Would probably be good to assert here that the id is different.

**Review by Darksonn — COMMENTED** [review]
Panics on spawned tasks do not ensure that the test fails. You have to ensure that the test fails if the panic happens. I commented on two of them, but it applies to many more tests.

File: tokio/tests/task_id.rs [hunk 31]
```diff
@@ -0,0 +1,287 @@
+#![warn(rust_2018_idioms)]
+#![allow(clippy::declare_interior_mutable_const)]
+#![cfg(all(feature = "full", tokio_unstable, not(tokio_wasi)))]
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:3]: Except for the panic-location tests, the tests here should work under wasm. You can disable specific tests under wasm with `#[cfg_attr(tokio_wasm, ignore)]`.
```suggestion
#![cfg(all(feature = "full", tokio_unstable))]
```

File: tokio/tests/task_id.rs [hunk 32]
```diff
@@ -0,0 +1,287 @@
...
+        fn drop(&mut self) {
+            let _ = self.tx.take().unwrap().send(task::id());
+        }
+    }
+
+    let (tx, rx) = oneshot::channel();
+    let handle = tokio::spawn(MyFuture { tx: Some(tx) });
+    let id = handle.id();
+    handle.abort();
+    assert_eq!(rx.await.unwrap(), id);
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:122]:
```suggestion
    handle.abort();
    assert!(handle.await.unwrap_err().is_cancelled());
    assert_eq!(rx.await.unwrap(), id);
```

File: tokio/tests/task_id.rs [hunk 33]
```diff
@@ -0,0 +1,287 @@
...
+    let (tx_output, rx_output) = oneshot::channel();
+    let (tx_future, rx_future) = oneshot::channel();
+    let handle = tokio::spawn(MyFuture {
+        tx_output: Some(tx_output),
+        tx_future: Some(tx_future),
+    });
+    let id = handle.id();
+    rx_future.await.unwrap();
+    drop(handle);
+    assert_eq!(rx_output.await.unwrap(), id);
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:193]: We can verify in the test that the output has not yet been dropped when we drop the handle.
```suggestion
    assert!(rx_output.try_recv().is_err());
    drop(handle);
    assert_eq!(rx_output.await.unwrap(), id);
```

File: tokio/tests/task_id.rs [hunk 34]
```diff
@@ -0,0 +1,287 @@
...
+        fn poll(mut self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Self::Output> {
+            Poll::Ready(MyOutput { tx: self.tx.take() })
+        }
+    }
+
+    let (tx, rx) = oneshot::channel();
+    let handle = tokio::spawn(MyFuture { tx: Some(tx) });
+    let id = handle.id();
+    drop(handle);
+    assert_eq!(rx.await.unwrap(), id);
```
Comment (Darksonn) [inline tokio/tests/task_id.rs:153]:
```suggestion
    drop(handle);
    assert!(rx.try_recv().is_err());
    assert_eq!(rx.await.unwrap(), id);
```

**Review by Darksonn — APPROVED** [review]
Looks good to me.
