### PR TITLE
broadcast: Stop notifying after we've woken all wakers

### LINKED ISSUE #5923: Quadratic slowdown in latency of `tokio::sync::broadcast::Sender::send` as the number of `Receiver`s increases, when each receiver is running in its own single-threaded runtime
**Version**

```
❯ cargo tree | grep tokio
└── tokio v1.30.0
    └── tokio-macros v2.1.0 (proc-macro)
```

**Platform**

```
❯ uname -a
Linux ogopogo 6.1.41 #1-NixOS SMP PREEMPT_DYNAMIC Mon Jul 24 16:55:35 UTC 2023 x86_64 GNU/Linux
```

**Description**

In an application that launches many threads (up to hundreds) each of which runs a `select` loop which polls on `tokio::sync::broadcast::Receiver::recv()`, calls to the `send` half of that channel sporadically get quadratically slower, up to minutes, as the number of receivers starts to increase past around 40. This behavior is *worse* (by about half an order of magnitude) if running in release mode. To demonstrate, I've written the following repro, which outputs a CSV :

```rust
use std::thread;
use std::time::Instant;
use std::{sync::Arc, time::Duration};

use tokio::select;
use tokio::sync::broadcast;
use tokio::time::sleep;

const BUFFER_SIZE: usize = 64;

async fn recv_loop(tx: Arc<broadcast::Sender<usize>>) {
    let mut rx = tx.subscribe();
    loop {
        select! {
            _ = sleep(Duration::from_millis(100)) => {}
            res = rx.recv() => {
                if matches!(res, Err(broadcast::error::RecvError::Closed)) {
                    break;
                }
            }
        }
    }
}

fn run_test(num_subscribers: usize) -> Duration {
    let (tx, _) = broadcast::channel(BUFFER_SIZE);
    let tx = Arc::new(tx);

    for _ in 0..num_subscribers {
        let tx = tx.clone();

        thread::spawn(move || {
            let runtime = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .max_blocking_threads(1)
                .build()
                .unwrap();

            runtime.block_on(recv_loop(tx));
        });
    }

    let start = Instant::now();
    let _ = tx.send(0);
    start.elapsed()
}

fn main() {
    for num_subscribers in 30..120 {
        let dur = run_test(num_subscribers);
        println!("{num_subscribers},{}", dur.as_nanos());
    }
}
```

And plotted the results in both debug and release mode when run on my machine:

plot

### PR DESCRIPTION
**Pull request by glittershark**
## Motivation

Fix #5923

## Solution
Unboundedly looping within `notify_rx` as long as there are still available wakers causes a quadratic slowdown as receivers which are looping receiving from the channel are added. Instead of continually waiting for new wakers, this commit modifies `notify_rx` to stop trying to wake wakers once we've notified a number of wakers greater than or equal to whatever the number of active wakers was when we started notifying.

### CODE REVIEW

File: tokio/src/sync/broadcast.rs [hunk 1]
```diff
@@ -852,6 +855,10 @@ impl<T> Shared<T> {
 
             // Acquire the lock again.
             tail = self.tail.lock();
+
+            if woken >= active_receivers {
+                break;
+            }
```
Comment (Darksonn) [inline tokio/src/sync/broadcast.rs:861]: Please move this above the call to `lock` and replace the break with return. That will avoid unnecessarily locking the mutex.

**Review by Darksonn — COMMENTED** [review]
Thanks for the PR!

File: tokio/src/sync/broadcast.rs (hunk 1 above)
Comment (glittershark) [reply tokio/src/sync/broadcast.rs:861]: Done.

**Comment by Darksonn** [comment]
Hmm, there's an alternate approach: Move everything in the list into a separate list immediately, then empty the separate list. I think that I would prefer that approach because it is simple to verify the correctness. Additionally, we already do this elsewhere, so it makes us more consistent across the codebase.

You can find an existing implementation of this here:

https://github.com/tokio-rs/tokio/blob/ad58664590d4b91ed8c0bcb6ef30884b9ae9a18f/tokio/src/sync/notify.rs#L618-L691

**Comment by glittershark** [comment]
@Darksonn done, I think

**Comment by Darksonn** [comment]
Looks reasonable to me. Does this version also fix the performance issue?

**Comment by wathenjiang** [comment]
I believe the scope of lock condition can be reduced. The method `Shared.notify_rx` could be written in the following way:
```rust
impl<T> Shared<T> {
    fn notify_rx<'a, 'b: 'a>(&'b self, mut tail: MutexGuard<'a, Tail>) {
        // It is critical for `GuardedLinkedList` safety that the guard node is
        // pinned in memory and is not dropped until the guarded list is dropped.
        let guard = Waiter::new();
        pin!(guard);

        // We move all waiters to a secondary list. It uses a `GuardedLinkedList`
        // underneath to allow every waiter to safely remove itself from it.
        //
        // * This list will be still guarded by the `waiters` lock.
        //   `NotifyWaitersList` wrapper makes sure we hold the lock to modify it.
        // * This wrapper will empty the list on drop. It is critical for safety
        //   that we will not leave any list entry with a pointer to the local
        //   guard node after this function returns / panics.
        let mut list = WaitersList::new(std::mem::take(&mut tail.waiters), guard.as_ref(), self);

        let mut wakers = WakeList::new();
        'outer: loop {
            // Because all waiter in tail.waiters has been moved to the secondary list, so we can drop the lock here.
            drop(tail);
            while wakers.can_push() {
                match list.pop_back() {
                    Some(mut waiter) => {
                        // Safety: `tail` lock is still held.
                        let waiter = unsafe { waiter.as_mut() };

                        assert!(waiter.queued);
                        waiter.queued = false;

                        if let Some(waker) = waiter.waker.take() {
                            wakers.push(waker);
                        }
                    }
                    None => {
                        break 'outer;
                    }
                }
            }

            // Before we acquire the lock again all sorts of things can happen:
            // some waiters may remove themselves from the list and new waiters
            // may be added. This is fine since at worst we will unnecessarily
            // wake up waiters which will then queue themselves again.

            wakers.wake_all();

            // Acquire the lock again.
            tail = self.tail.lock();
        }

        wakers.wake_all();
    }
}
```

**Comment by Darksonn** [comment]
No, we can't do that. it is important that we hold the lock when calling `pop_back`. Otherwise, the destructor of the waiter could remove it from the linked list in parallel with the call to `pop_back`, which would be a data race. Since this is unsafe code, it would not be caught by the compiler, but it is still wrong.

**Comment by wathenjiang** [comment]
> No, we can't do that. it is important that we hold the lock when calling `pop_back`. Otherwise, the destructor of the waiter could remove it from the linked list in parallel with the call to `pop_back`, which would be a data race. Since this is unsafe code, it would not be caught by the compiler, but it is still wrong.

You are right, the lock should be held while doing the loop. The following code may cause data race.

**Comment by glittershark** [comment]
> Looks reasonable to me. Does this version also fix the performance issue?

yep!

debug
