### PR TITLE
rt: avoid dropping a task in calls to wake()

### LINKED ISSUE #1929: BorrowMutError in tokio-0.2.4
panics in 0.2.4, worked in 0.2.2

```rust
thread 'actix-rt:worker:3' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1165:5
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: std::panicking::begin_panic
  14: std::panicking::begin_panic
  15: core::result::Result<T,E>::expect
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:960
  16: core::cell::RefCell<T>::borrow_mut
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/cell.rs:869
  17: actix_utils::mpsc::Receiver<T>::close
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-utils-1.0.0-alpha.3/src/mpsc.rs:135
  18: <actix_utils::mpsc::Receiver<T> as core::ops::drop::Drop>::drop
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-utils-1.0.0-alpha.3/src/mpsc.rs:171
  19: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  20: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  21: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  22: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  23: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  24: tokio::task::core::Core<T>::transition_to_consumed
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/core.rs:106
  25: tokio::task::harness::Harness<T,S>::do_cancel::{{closure}}::{{closure}}
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:363
  26: core::ops::function::FnOnce::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
  27: <getopts::OptGroup as core::clone::Clone>::clone
  28: std::panicking::try::do_call
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  30: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  31: <getopts::OptGroup as core::clone::Clone>::clone
  32: tokio::task::harness::Harness<T,S>::do_cancel::{{closure}}
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:361
  33: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/loom/std/causal_cell.rs:41
  34: tokio::task::harness::Harness<T,S>::do_cancel
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:359
  35: tokio::task::harness::Harness<T,S>::cancel
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:342
  36: tokio::task::raw::cancel
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/raw.rs:196
  37: tokio::task::raw::RawTask::cancel_from_queue
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/raw.rs:145
  38: tokio::task::Task<S>::shutdown
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/mod.rs:385
  39: tokio::task::queue::RemoteQueue<S>::schedule
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/queue.rs:307
  40: <tokio::task::local::Scheduler as tokio::task::Schedule>::schedule
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/local.rs:348
  41: tokio::task::harness::Harness<T,S>::wake_by_ref
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:315
  42: tokio::task::harness::Harness<T,S>::wake_by_val
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:299
  43: tokio::task::waker::wake_by_val
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/waker.rs:84
  44: core::task::wake::Waker::wake
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/task/wake.rs:252
```

### PR DESCRIPTION
**Pull request by carllerche**
Calls to tasks should not be nested. Currently, while a task is being
executed and the runtime is shutting down, a call to wake() can result
in the wake target to be dropped. This, in turn, results in the drop
handler being called.

If the user holds a ref cell borrow, a mutex guard, or any such value,
dropping the task inline can result in a deadlock.

The fix is to permit tasks to be scheduled during the shutdown process
and dropping the tasks once they are popped from the queue.

Fixes #1929, #1886

This only fixes single threaded schedulers. I have net yet reproduced the bug in
the threaded scheduler but will continue to explore.

### CODE REVIEW

File: tokio/src/runtime/basic_scheduler.rs [hunk 1]
```diff
@@ -298,10 +302,16 @@ where
...
+        loop {
             unsafe {
                 self.scheduler.queues.drain_pending_drop();
+                self.scheduler.queues.drain_queues();
+
+                if !self.scheduler.queues.has_tasks_remaining() {
+                    break;
+                }
+
+                self.local.park.park().ok().expect("park failed");
```
Comment (hawkw) [inline tokio/src/runtime/basic_scheduler.rs]: Nit/TIOLI: this is safe to call, right? Maybe it should be moved out of the `unsafe` block?

File: tokio/src/task/queue.rs [hunk 2]
```diff
@@ -233,6 +233,16 @@ where
         self.drain_pending_drop();
     }
 
+    /// Drain run queues, shutting down any task.
```
Comment (hawkw) [inline tokio/src/task/queue.rs]: Nit:
```suggestion
    /// Drain both the local and remote run queues, shutting down any tasks.
```

File: tokio/tests/task_local_set.rs [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+    });
+
+    // Drop the LocalSet
+    drop(local);
+}
+
+fn rt() -> Runtime {
+    tokio::runtime::Builder::new()
+        .basic_scheduler()
+        .enable_all()
```
Comment (hawkw) [inline tokio/tests/task_local_set.rs]: Nit: I don't _think_ we need to enable timers/io in these tests...is there any test speed penalty for enabling them if we don't use them?

File: tokio/src/runtime/basic_scheduler.rs [hunk 4]
```diff
@@ -161,7 +161,7 @@ impl Spawner {
         F::Output: Send + 'static,
     {
         let (task, handle) = task::joinable(future);
-        self.scheduler.schedule(task);
+        self.scheduler.schedule(task, true);
```
Comment (hawkw) [inline tokio/src/runtime/basic_scheduler.rs]: The meaning of the bool parameter here is a little unclear at the callsite, I'd prefer it if it was clearer what the "false" means. But, I don't think the other options I can think of (having separate `schedule` and `schedule_spawn` fns, or using an enum) are really worth it...

File: tokio/tests/task_local_set.rs [hunk 5]
```diff
@@ -0,0 +1,50 @@
+#![warn(rust_2018_idioms)]
+#![cfg(feature = "full")]
+
+use tokio::runtime::Runtime;
+use tokio::sync::oneshot;
+use tokio::task::{self, LocalSet};
+
+#[test]
+fn acquire_mutex_in_drop() {
```
Comment (hawkw) [inline tokio/tests/task_local_set.rs]: The failure mode for this is a deadlock, right? Should we maybe do something similar to this test and add a timeout? https://github.com/tokio-rs/tokio/blob/efb4b67a5415c1feeaa6668618243c89f7b601eb/tokio/src/task/local.rs#L732-L741

Comment (carllerche) [reply tokio/tests/task_local_set.rs]: I rather it just deadlock tbh... timeouts don't seem great.

**Comment by carllerche** [comment]
It seems like CI isn't reporting back :(

File: tokio/tests/task_local_set.rs (hunk 3 above)
Comment (carllerche) [reply tokio/tests/task_local_set.rs]: doubtful :shrug:
