### PR TITLE
codec: docs: fix length_delimited doc description and make examples testable

### LINKED ISSUE #6604: LengthDelimitedCodec misses that last N bytes of the frame with num_skip(0)
**Version**

tokio master branch (14c17fc09656a30230177b600bacceb9db33e942, tokio 1.38.0), also tokio-util 0.7.11.

**Platform**

Linux

**Description**

The [documentation](https://docs.rs/tokio-util/latest/tokio_util/codec/length_delimited/index.html#example-1) gives this example:

```rust
LengthDelimitedCodec::builder()
    .length_field_offset(0) // default value
    .length_field_type::<u16>()
    .length_adjustment(0)   // default value
    .num_skip(0) // Do not strip frame header
    .new_read(io);
```

The following frame will be decoded as such:

```rust
         INPUT                           DECODED
+-- len ---+--- Payload ---+     +-- len ---+--- Payload ---+
| \x00\x0B |  Hello world  | --> | \x00\x0B |  Hello world  |
+----------+---------------+     +----------+---------------+
```

However, the following (new) test fails in tokio-util/tests/length_delimited.rs:

```rust
#[test]
fn read_single_frame_skip_none() {
    let mut d: Vec<u8> = vec![];
    d.extend_from_slice(b"\x00\x0BHello world");

    let io = length_delimited::Builder::new()
        .length_field_offset(0)
        .length_field_type::<u16>()
        .length_adjustment(0)
        .num_skip(0)
        .new_read(mock! {
            data(&d),
        });
    pin_mut!(io);

    assert_next_eq!(io, b"\x00\x0BHello world");
    assert_done!(io);
}
```

Error message:

```
thread 'read_single_frame_skip_none' panicked at tokio-util/tests/length_delimited.rs:389:5:
assertion `left == right` failed
  left: b"\0\x0bHello wor"
 right: [0, 11, 72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100]
```

The last two bytes of "world" is missing. With a longer size prefix (u32), the number of missing byte increases (4). It appears to me that the logic that reads the size advances the pointer, but this is incorrectly adjusted later, when num_skip(0) is taken into account.

A possible workaround:

```
        .length_adjustment(2) # 2 must match the size prefix size.
```

### PR DESCRIPTION
**Pull request by name1e5s**
## Motivation

According to [comment](https://github.com/tokio-rs/tokio/issues/6604#issuecomment-2150408931) in #6604, some examples for `length_delimited` do not fit the real behavior. This PR fix the document and add tests to the examples.

Close #6604

## Solution

Fix the docs.

Swap the order of example 1 and 2 to make it more easier to understand.

### CODE REVIEW

File: tokio-util/src/codec/length_delimited.rs [hunk 1]
```diff
@@ -113,30 +115,35 @@
...
-//! +----------+---------------+     +---------------+
+//!          INPUT                           DECODED
+//! +-- len ---+--- Payload ---+     +-- len ---+--- Payload ---+
+//! | \x00\x0B |  Hello world  | --> | \x00\x0B |  Hello world  |
+//! +----------+---------------+     +----------+---------------+
 //! ```
 //!
 //! This is similar to the first example, the only difference is that the
-//! frame head is **not** included in the yielded `BytesMut` value.
+//! frame head is **included** in the yielded `BytesMut` value. To archive
```
Comment (Darksonn) [inline tokio-util/src/codec/length_delimited.rs:144]:
```suggestion
//! frame head is **included** in the yielded `BytesMut` value. To achieve
```

File: tokio-util/src/codec/length_delimited.rs [hunk 2]
```diff
@@ -113,30 +115,35 @@
...
+//! this, we need to add header size to the length with `length_adjustment`,
```
Comment (Darksonn) [inline tokio-util/src/codec/length_delimited.rs:145]:
```suggestion
//! this, we need to add the header size to the length with `length_adjustment`,
```

**Review by Darksonn — COMMENTED** [review]
This looks like a good improvement. A few nits:

File: tokio-util/src/codec/length_delimited.rs [hunk 3]
```diff
@@ -79,26 +79,28 @@
 //! frame head in the yielded `BytesMut`.
```
Comment (mox692) [inline tokio-util/src/codec/length_delimited.rs:79]: > including the frame head in the yielded `BytesMut`.

Perhaps the comment here should also be updated to `omitting` instead of `including`?

Comment (name1e5s) [reply tokio-util/src/codec/length_delimited.rs:79]: Yes, I forgot this. All `including`/`omitting` is corrected now.

**Review by mox692 — APPROVED** [review]
Thanks, looks good to me!
