### PR TITLE
Error Creating PollEvented for RawFd #2413

### LINKED ISSUE #2413: Error Creating PollEvented for RawFd
## Version

0.2.18

## Platform

19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

## Description
I am attempting to create PollEvented from a RawFd, but it looks to be getting an invalid token. 

    [2020-04-17T17:27:17Z TRACE mio::sys::unix::kqueue] registering; token=Token(34359738368); interests=Readable | Writable | Error | Hup

This is leading to an IO Error for invalid argument

Code occurring inside an async context:

```
let mio_ev = mio::unix::EventedFd(&args.fd);
debug!("Create event for {:?}", mio_ev);
let ev = tokio::io::PollEvented::new(mio_ev).map_err(|e| {
   error!("Failed to create evented");
   Error::Io(e)
})?;
```

When I create a mio event manually, I do not have an issue.

```
let ev = mio::unix::EventedFd(&self.fd);
let ready = mio::Ready::readable();
let opts = mio::PollOpt::edge();
ev.register(&self.poll, mio::Token(0), ready, opts).map_err(Error::Io)?;
```

### PR DESCRIPTION
**Pull request by dbcfd**
Add additional methods to allow PollEvented to be created with an appropriate
`mio::Ready` state so that it can be properly registered with the reactor.

Fixes #2413

### CODE REVIEW

**Comment by Darksonn** [comment]
You have some warnings that caused the CI to fail.

**Comment by dbcfd** [comment]
@Darksonn There's currently an unused method now in the PR. I don't think it would have any impact by removing it (seems to be internal to io), but wasn't sure if I should just remove it.

**Comment by Darksonn** [comment]
Yeah, in this case it should be removed.

**Comment by dbcfd** [comment]
@Darksonn Removed.

File: tokio/src/io/registration.rs [hunk 1]
```diff
@@ -63,12 +63,34 @@ impl Registration {
     /// from a future driven by a tokio runtime, otherwise runtime can be set
     /// explicitly with [`Handle::enter`](crate::runtime::Handle::enter) function.
     pub fn new<T>(io: &T) -> io::Result<Registration>
+    where
+        T: Evented,
+    {
+        Registration::new_with_ready(io, mio::Ready::all())
+    }
+
+    /// Registers the I/O resource with the default reactor, for a specific `mio::Ready` state.
```
Comment (kleimkuhler) [inline tokio/src/io/registration.rs:72]: It may be worth noting here that this will not register HUP interest. `Ready::all()` also registers interest in errors, but those should trigger without registration anyways.

Comment (dbcfd) [reply tokio/src/io/registration.rs:72]: Should we combine the readiness they provide with hup and error?

**Comment by dbcfd** [comment]
>  If they intend to only read from the source (that is also writable), they may wonder why use new instead of new_with_ready.

I think this might be best addressed with documentation. Indicate that new_with_ready should be used if your source does not support both read and write.

**Comment by kleimkuhler** [comment]
> I think this might be best addressed with documentation. Indicate that new_with_ready should be used if your source does not support both read and write.

I would be good with that! If you can add that to the documentation then I should be good for approving this.

File: tokio/src/io/registration.rs (hunk 1 above)
Comment (kleimkuhler) [reply tokio/src/io/registration.rs:72]: My concern about that is that if a user *really* does not want to register HUP interest for example, then `new_with_ready` seems like the method that should be used. It would be surprising if we still automatically register that.

Comment (dbcfd) [reply tokio/src/io/registration.rs:72]: I've added additional documentation to PollEvented and Registration. Let me know if that clarifies things.

Comment (kleimkuhler) [reply tokio/src/io/registration.rs:72]: Yep this looks good.

**Comment by carllerche** [comment]
I think we are going to have to deprecate PollEvented long term (as we look into things like uring).

I'm ok w/ merging this now. That said, could we also try to solve the problem **without** PollEvented. Should we add a `RawFd` type that is hooked up w/ the reactor?

**Comment by dbcfd** [comment]
Would love just being able to hook a rawfd type up to reactor for polling.

**Comment by Darksonn** [comment]
I am merging this per @carllerche's comments. Please see #2519 for solving the problem without `PollEvented`.
